// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: rpc/proto/battle.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ElementRelation int32

const (
	ElementRelation_OVER_POWER   ElementRelation = 0
	ElementRelation_OVER_POWERED ElementRelation = 1
	ElementRelation_NURTURE      ElementRelation = 2
	ElementRelation_NURTURED     ElementRelation = 3
	ElementRelation_TIE          ElementRelation = 4
)

// Enum value maps for ElementRelation.
var (
	ElementRelation_name = map[int32]string{
		0: "OVER_POWER",
		1: "OVER_POWERED",
		2: "NURTURE",
		3: "NURTURED",
		4: "TIE",
	}
	ElementRelation_value = map[string]int32{
		"OVER_POWER":   0,
		"OVER_POWERED": 1,
		"NURTURE":      2,
		"NURTURED":     3,
		"TIE":          4,
	}
)

func (x ElementRelation) Enum() *ElementRelation {
	p := new(ElementRelation)
	*p = x
	return p
}

func (x ElementRelation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ElementRelation) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_battle_proto_enumTypes[0].Descriptor()
}

func (ElementRelation) Type() protoreflect.EnumType {
	return &file_rpc_proto_battle_proto_enumTypes[0]
}

func (x ElementRelation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ElementRelation.Descriptor instead.
func (ElementRelation) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_battle_proto_rawDescGZIP(), []int{0}
}

type GameResultType int32

const (
	GameResultType_GAME_NORMAL  GameResultType = 0
	GameResultType_GAME_KO      GameResultType = 1
	GameResultType_GAME_TIE     GameResultType = 2
	GameResultType_GAME_ABORTED GameResultType = 3
)

// Enum value maps for GameResultType.
var (
	GameResultType_name = map[int32]string{
		0: "GAME_NORMAL",
		1: "GAME_KO",
		2: "GAME_TIE",
		3: "GAME_ABORTED",
	}
	GameResultType_value = map[string]int32{
		"GAME_NORMAL":  0,
		"GAME_KO":      1,
		"GAME_TIE":     2,
		"GAME_ABORTED": 3,
	}
)

func (x GameResultType) Enum() *GameResultType {
	p := new(GameResultType)
	*p = x
	return p
}

func (x GameResultType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameResultType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_battle_proto_enumTypes[1].Descriptor()
}

func (GameResultType) Type() protoreflect.EnumType {
	return &file_rpc_proto_battle_proto_enumTypes[1]
}

func (x GameResultType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameResultType.Descriptor instead.
func (GameResultType) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_battle_proto_rawDescGZIP(), []int{1}
}

type PlayerGameResultStatus int32

const (
	PlayerGameResultStatus_PLAYER_ABORTED PlayerGameResultStatus = 0
	PlayerGameResultStatus_PLAYER_WIN     PlayerGameResultStatus = 1
	PlayerGameResultStatus_PLAYER_LOSE    PlayerGameResultStatus = 2
	PlayerGameResultStatus_PLAYER_TIE     PlayerGameResultStatus = 3
)

// Enum value maps for PlayerGameResultStatus.
var (
	PlayerGameResultStatus_name = map[int32]string{
		0: "PLAYER_ABORTED",
		1: "PLAYER_WIN",
		2: "PLAYER_LOSE",
		3: "PLAYER_TIE",
	}
	PlayerGameResultStatus_value = map[string]int32{
		"PLAYER_ABORTED": 0,
		"PLAYER_WIN":     1,
		"PLAYER_LOSE":    2,
		"PLAYER_TIE":     3,
	}
)

func (x PlayerGameResultStatus) Enum() *PlayerGameResultStatus {
	p := new(PlayerGameResultStatus)
	*p = x
	return p
}

func (x PlayerGameResultStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerGameResultStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_battle_proto_enumTypes[2].Descriptor()
}

func (PlayerGameResultStatus) Type() protoreflect.EnumType {
	return &file_rpc_proto_battle_proto_enumTypes[2]
}

func (x PlayerGameResultStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerGameResultStatus.Descriptor instead.
func (PlayerGameResultStatus) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_battle_proto_rawDescGZIP(), []int{2}
}

type BattleEffectType int32

const (
	BattleEffectType_ATTACK BattleEffectType = 0
	BattleEffectType_HEAL   BattleEffectType = 1
)

// Enum value maps for BattleEffectType.
var (
	BattleEffectType_name = map[int32]string{
		0: "ATTACK",
		1: "HEAL",
	}
	BattleEffectType_value = map[string]int32{
		"ATTACK": 0,
		"HEAL":   1,
	}
)

func (x BattleEffectType) Enum() *BattleEffectType {
	p := new(BattleEffectType)
	*p = x
	return p
}

func (x BattleEffectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleEffectType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_battle_proto_enumTypes[3].Descriptor()
}

func (BattleEffectType) Type() protoreflect.EnumType {
	return &file_rpc_proto_battle_proto_enumTypes[3]
}

func (x BattleEffectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleEffectType.Descriptor instead.
func (BattleEffectType) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_battle_proto_rawDescGZIP(), []int{3}
}

type RoundCompleteReason int32

const (
	RoundCompleteReason_ROUND_COMPLETE_NORMAL                      RoundCompleteReason = 0
	RoundCompleteReason_ROUND_COMPLETE_PLAYER_CONFIRMATION_TIMEOUT RoundCompleteReason = 1
	RoundCompleteReason_ROUND_COMPLETE_PLAYER_COMMITMENTS_TIMEOUT  RoundCompleteReason = 2
	RoundCompleteReason_ROUND_COMPLETE_PLAYER_CARDS_TIMEOUT        RoundCompleteReason = 3
	RoundCompleteReason_ROUND_COMPLETE_SERVER_CHAIN_TIMEOUT        RoundCompleteReason = 4
	RoundCompleteReason_ROUND_COMPLETE_SERVER_INTERNAL_TIMEOUT     RoundCompleteReason = 5
	RoundCompleteReason_ROUND_COMPLETE_PLAYER_SURRENDER            RoundCompleteReason = 6
)

// Enum value maps for RoundCompleteReason.
var (
	RoundCompleteReason_name = map[int32]string{
		0: "ROUND_COMPLETE_NORMAL",
		1: "ROUND_COMPLETE_PLAYER_CONFIRMATION_TIMEOUT",
		2: "ROUND_COMPLETE_PLAYER_COMMITMENTS_TIMEOUT",
		3: "ROUND_COMPLETE_PLAYER_CARDS_TIMEOUT",
		4: "ROUND_COMPLETE_SERVER_CHAIN_TIMEOUT",
		5: "ROUND_COMPLETE_SERVER_INTERNAL_TIMEOUT",
		6: "ROUND_COMPLETE_PLAYER_SURRENDER",
	}
	RoundCompleteReason_value = map[string]int32{
		"ROUND_COMPLETE_NORMAL":                      0,
		"ROUND_COMPLETE_PLAYER_CONFIRMATION_TIMEOUT": 1,
		"ROUND_COMPLETE_PLAYER_COMMITMENTS_TIMEOUT":  2,
		"ROUND_COMPLETE_PLAYER_CARDS_TIMEOUT":        3,
		"ROUND_COMPLETE_SERVER_CHAIN_TIMEOUT":        4,
		"ROUND_COMPLETE_SERVER_INTERNAL_TIMEOUT":     5,
		"ROUND_COMPLETE_PLAYER_SURRENDER":            6,
	}
)

func (x RoundCompleteReason) Enum() *RoundCompleteReason {
	p := new(RoundCompleteReason)
	*p = x
	return p
}

func (x RoundCompleteReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoundCompleteReason) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_battle_proto_enumTypes[4].Descriptor()
}

func (RoundCompleteReason) Type() protoreflect.EnumType {
	return &file_rpc_proto_battle_proto_enumTypes[4]
}

func (x RoundCompleteReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoundCompleteReason.Descriptor instead.
func (RoundCompleteReason) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_battle_proto_rawDescGZIP(), []int{4}
}

type PlayerCardStat struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CardNumber       int32                  `protobuf:"varint,1,opt,name=CardNumber,proto3" json:"CardNumber,omitempty"`
	CardID           int32                  `protobuf:"varint,2,opt,name=CardID,proto3" json:"CardID,omitempty"`
	HPBefore         int32                  `protobuf:"varint,3,opt,name=HPBefore,proto3" json:"HPBefore,omitempty"`
	HPAfter          int32                  `protobuf:"varint,4,opt,name=HPAfter,proto3" json:"HPAfter,omitempty"`
	MultiplierBefore int32                  `protobuf:"varint,5,opt,name=MultiplierBefore,proto3" json:"MultiplierBefore,omitempty"`
	MultiplierAfter  int32                  `protobuf:"varint,6,opt,name=MultiplierAfter,proto3" json:"MultiplierAfter,omitempty"`
	Effects          []*BattleEffect        `protobuf:"bytes,7,rep,name=Effects,proto3" json:"Effects,omitempty"`
	Description      string                 `protobuf:"bytes,8,opt,name=Description,proto3" json:"Description,omitempty"`
	ElementRelation  ElementRelation        `protobuf:"varint,9,opt,name=ElementRelation,proto3,enum=battle.ElementRelation" json:"ElementRelation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlayerCardStat) Reset() {
	*x = PlayerCardStat{}
	mi := &file_rpc_proto_battle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerCardStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerCardStat) ProtoMessage() {}

func (x *PlayerCardStat) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_battle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerCardStat.ProtoReflect.Descriptor instead.
func (*PlayerCardStat) Descriptor() ([]byte, []int) {
	return file_rpc_proto_battle_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerCardStat) GetCardNumber() int32 {
	if x != nil {
		return x.CardNumber
	}
	return 0
}

func (x *PlayerCardStat) GetCardID() int32 {
	if x != nil {
		return x.CardID
	}
	return 0
}

func (x *PlayerCardStat) GetHPBefore() int32 {
	if x != nil {
		return x.HPBefore
	}
	return 0
}

func (x *PlayerCardStat) GetHPAfter() int32 {
	if x != nil {
		return x.HPAfter
	}
	return 0
}

func (x *PlayerCardStat) GetMultiplierBefore() int32 {
	if x != nil {
		return x.MultiplierBefore
	}
	return 0
}

func (x *PlayerCardStat) GetMultiplierAfter() int32 {
	if x != nil {
		return x.MultiplierAfter
	}
	return 0
}

func (x *PlayerCardStat) GetEffects() []*BattleEffect {
	if x != nil {
		return x.Effects
	}
	return nil
}

func (x *PlayerCardStat) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PlayerCardStat) GetElementRelation() ElementRelation {
	if x != nil {
		return x.ElementRelation
	}
	return ElementRelation_OVER_POWER
}

type PlayerRoundStat struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlayerId         int64                  `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	TemporaryAddress string                 `protobuf:"bytes,2,opt,name=TemporaryAddress,proto3" json:"TemporaryAddress,omitempty"`
	LostHP           int32                  `protobuf:"varint,3,opt,name=LostHP,proto3" json:"LostHP,omitempty"`
	CardStats        []*PlayerCardStat      `protobuf:"bytes,4,rep,name=CardStats,proto3" json:"CardStats,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlayerRoundStat) Reset() {
	*x = PlayerRoundStat{}
	mi := &file_rpc_proto_battle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRoundStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRoundStat) ProtoMessage() {}

func (x *PlayerRoundStat) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_battle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRoundStat.ProtoReflect.Descriptor instead.
func (*PlayerRoundStat) Descriptor() ([]byte, []int) {
	return file_rpc_proto_battle_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerRoundStat) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerRoundStat) GetTemporaryAddress() string {
	if x != nil {
		return x.TemporaryAddress
	}
	return ""
}

func (x *PlayerRoundStat) GetLostHP() int32 {
	if x != nil {
		return x.LostHP
	}
	return 0
}

func (x *PlayerRoundStat) GetCardStats() []*PlayerCardStat {
	if x != nil {
		return x.CardStats
	}
	return nil
}

type RoundResult struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Players             []*PlayerRoundStat     `protobuf:"bytes,1,rep,name=Players,proto3" json:"Players,omitempty"`
	RoundNumber         uint32                 `protobuf:"varint,2,opt,name=RoundNumber,proto3" json:"RoundNumber,omitempty"`
	IsGameOver          bool                   `protobuf:"varint,3,opt,name=IsGameOver,proto3" json:"IsGameOver,omitempty"`
	RoundEndTime        uint64                 `protobuf:"varint,4,opt,name=RoundEndTime,proto3" json:"RoundEndTime,omitempty"`
	RoundConfirmTimeout uint64                 `protobuf:"varint,5,opt,name=RoundConfirmTimeout,proto3" json:"RoundConfirmTimeout,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RoundResult) Reset() {
	*x = RoundResult{}
	mi := &file_rpc_proto_battle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundResult) ProtoMessage() {}

func (x *RoundResult) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_battle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundResult.ProtoReflect.Descriptor instead.
func (*RoundResult) Descriptor() ([]byte, []int) {
	return file_rpc_proto_battle_proto_rawDescGZIP(), []int{2}
}

func (x *RoundResult) GetPlayers() []*PlayerRoundStat {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *RoundResult) GetRoundNumber() uint32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *RoundResult) GetIsGameOver() bool {
	if x != nil {
		return x.IsGameOver
	}
	return false
}

func (x *RoundResult) GetRoundEndTime() uint64 {
	if x != nil {
		return x.RoundEndTime
	}
	return 0
}

func (x *RoundResult) GetRoundConfirmTimeout() uint64 {
	if x != nil {
		return x.RoundConfirmTimeout
	}
	return 0
}

type PlayerReward struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	PlayerId               int64                  `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	TemporaryAddress       string                 `protobuf:"bytes,2,opt,name=TemporaryAddress,proto3" json:"TemporaryAddress,omitempty"`
	TokenChange            int32                  `protobuf:"varint,3,opt,name=TokenChange,proto3" json:"TokenChange,omitempty"`
	PointChange            int32                  `protobuf:"varint,4,opt,name=PointChange,proto3" json:"PointChange,omitempty"`
	Offline                bool                   `protobuf:"varint,5,opt,name=Offline,proto3" json:"Offline,omitempty"`
	Surrendered            bool                   `protobuf:"varint,6,opt,name=Surrendered,proto3" json:"Surrendered,omitempty"`
	PlayerGameResultStatus PlayerGameResultStatus `protobuf:"varint,7,opt,name=PlayerGameResultStatus,proto3,enum=battle.PlayerGameResultStatus" json:"PlayerGameResultStatus,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PlayerReward) Reset() {
	*x = PlayerReward{}
	mi := &file_rpc_proto_battle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerReward) ProtoMessage() {}

func (x *PlayerReward) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_battle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerReward.ProtoReflect.Descriptor instead.
func (*PlayerReward) Descriptor() ([]byte, []int) {
	return file_rpc_proto_battle_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerReward) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerReward) GetTemporaryAddress() string {
	if x != nil {
		return x.TemporaryAddress
	}
	return ""
}

func (x *PlayerReward) GetTokenChange() int32 {
	if x != nil {
		return x.TokenChange
	}
	return 0
}

func (x *PlayerReward) GetPointChange() int32 {
	if x != nil {
		return x.PointChange
	}
	return 0
}

func (x *PlayerReward) GetOffline() bool {
	if x != nil {
		return x.Offline
	}
	return false
}

func (x *PlayerReward) GetSurrendered() bool {
	if x != nil {
		return x.Surrendered
	}
	return false
}

func (x *PlayerReward) GetPlayerGameResultStatus() PlayerGameResultStatus {
	if x != nil {
		return x.PlayerGameResultStatus
	}
	return PlayerGameResultStatus_PLAYER_ABORTED
}

type BattleReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerRewards []*PlayerReward        `protobuf:"bytes,1,rep,name=PlayerRewards,proto3" json:"PlayerRewards,omitempty"`
	SystemFee     int32                  `protobuf:"varint,2,opt,name=SystemFee,proto3" json:"SystemFee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleReward) Reset() {
	*x = BattleReward{}
	mi := &file_rpc_proto_battle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleReward) ProtoMessage() {}

func (x *BattleReward) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_battle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleReward.ProtoReflect.Descriptor instead.
func (*BattleReward) Descriptor() ([]byte, []int) {
	return file_rpc_proto_battle_proto_rawDescGZIP(), []int{4}
}

func (x *BattleReward) GetPlayerRewards() []*PlayerReward {
	if x != nil {
		return x.PlayerRewards
	}
	return nil
}

func (x *BattleReward) GetSystemFee() int32 {
	if x != nil {
		return x.SystemFee
	}
	return 0
}

type GameResult struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Multiplier             int32                  `protobuf:"varint,1,opt,name=Multiplier,proto3" json:"Multiplier,omitempty"`
	WinnerPlayerId         int64                  `protobuf:"varint,2,opt,name=WinnerPlayerId,proto3" json:"WinnerPlayerId,omitempty"`
	WinnerTemporaryAddress string                 `protobuf:"bytes,3,opt,name=WinnerTemporaryAddress,proto3" json:"WinnerTemporaryAddress,omitempty"`
	GameResultType         GameResultType         `protobuf:"varint,5,opt,name=GameResultType,proto3,enum=battle.GameResultType" json:"GameResultType,omitempty"`
	Reward                 *BattleReward          `protobuf:"bytes,6,opt,name=Reward,proto3" json:"Reward,omitempty"`
	GameContinueTimeout    uint64                 `protobuf:"varint,7,opt,name=GameContinueTimeout,proto3" json:"GameContinueTimeout,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GameResult) Reset() {
	*x = GameResult{}
	mi := &file_rpc_proto_battle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameResult) ProtoMessage() {}

func (x *GameResult) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_battle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameResult.ProtoReflect.Descriptor instead.
func (*GameResult) Descriptor() ([]byte, []int) {
	return file_rpc_proto_battle_proto_rawDescGZIP(), []int{5}
}

func (x *GameResult) GetMultiplier() int32 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *GameResult) GetWinnerPlayerId() int64 {
	if x != nil {
		return x.WinnerPlayerId
	}
	return 0
}

func (x *GameResult) GetWinnerTemporaryAddress() string {
	if x != nil {
		return x.WinnerTemporaryAddress
	}
	return ""
}

func (x *GameResult) GetGameResultType() GameResultType {
	if x != nil {
		return x.GameResultType
	}
	return GameResultType_GAME_NORMAL
}

func (x *GameResult) GetReward() *BattleReward {
	if x != nil {
		return x.Reward
	}
	return nil
}

func (x *GameResult) GetGameContinueTimeout() uint64 {
	if x != nil {
		return x.GameContinueTimeout
	}
	return 0
}

type BattleEffect struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Type                   BattleEffectType       `protobuf:"varint,1,opt,name=Type,proto3,enum=battle.BattleEffectType" json:"Type,omitempty"`       // "attack" or "heal"
	Value                  int32                  `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`                                  // effect value
	TargetPlayerId         int64                  `protobuf:"varint,3,opt,name=TargetPlayerId,proto3" json:"TargetPlayerId,omitempty"`                // target player address
	TargetTemporaryAddress string                 `protobuf:"bytes,4,opt,name=TargetTemporaryAddress,proto3" json:"TargetTemporaryAddress,omitempty"` // target player address
	Description            string                 `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`                       // effect description
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BattleEffect) Reset() {
	*x = BattleEffect{}
	mi := &file_rpc_proto_battle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleEffect) ProtoMessage() {}

func (x *BattleEffect) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_battle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleEffect.ProtoReflect.Descriptor instead.
func (*BattleEffect) Descriptor() ([]byte, []int) {
	return file_rpc_proto_battle_proto_rawDescGZIP(), []int{6}
}

func (x *BattleEffect) GetType() BattleEffectType {
	if x != nil {
		return x.Type
	}
	return BattleEffectType_ATTACK
}

func (x *BattleEffect) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *BattleEffect) GetTargetPlayerId() int64 {
	if x != nil {
		return x.TargetPlayerId
	}
	return 0
}

func (x *BattleEffect) GetTargetTemporaryAddress() string {
	if x != nil {
		return x.TargetTemporaryAddress
	}
	return ""
}

func (x *BattleEffect) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_rpc_proto_battle_proto protoreflect.FileDescriptor

const file_rpc_proto_battle_proto_rawDesc = "" +
	"\n" +
	"\x16rpc/proto/battle.proto\x12\x06battle\"\xe9\x02\n" +
	"\x0ePlayerCardStat\x12\x1e\n" +
	"\n" +
	"CardNumber\x18\x01 \x01(\x05R\n" +
	"CardNumber\x12\x16\n" +
	"\x06CardID\x18\x02 \x01(\x05R\x06CardID\x12\x1a\n" +
	"\bHPBefore\x18\x03 \x01(\x05R\bHPBefore\x12\x18\n" +
	"\aHPAfter\x18\x04 \x01(\x05R\aHPAfter\x12*\n" +
	"\x10MultiplierBefore\x18\x05 \x01(\x05R\x10MultiplierBefore\x12(\n" +
	"\x0fMultiplierAfter\x18\x06 \x01(\x05R\x0fMultiplierAfter\x12.\n" +
	"\aEffects\x18\a \x03(\v2\x14.battle.BattleEffectR\aEffects\x12 \n" +
	"\vDescription\x18\b \x01(\tR\vDescription\x12A\n" +
	"\x0fElementRelation\x18\t \x01(\x0e2\x17.battle.ElementRelationR\x0fElementRelation\"\xa7\x01\n" +
	"\x0fPlayerRoundStat\x12\x1a\n" +
	"\bPlayerId\x18\x01 \x01(\x03R\bPlayerId\x12*\n" +
	"\x10TemporaryAddress\x18\x02 \x01(\tR\x10TemporaryAddress\x12\x16\n" +
	"\x06LostHP\x18\x03 \x01(\x05R\x06LostHP\x124\n" +
	"\tCardStats\x18\x04 \x03(\v2\x16.battle.PlayerCardStatR\tCardStats\"\xd8\x01\n" +
	"\vRoundResult\x121\n" +
	"\aPlayers\x18\x01 \x03(\v2\x17.battle.PlayerRoundStatR\aPlayers\x12 \n" +
	"\vRoundNumber\x18\x02 \x01(\rR\vRoundNumber\x12\x1e\n" +
	"\n" +
	"IsGameOver\x18\x03 \x01(\bR\n" +
	"IsGameOver\x12\"\n" +
	"\fRoundEndTime\x18\x04 \x01(\x04R\fRoundEndTime\x120\n" +
	"\x13RoundConfirmTimeout\x18\x05 \x01(\x04R\x13RoundConfirmTimeout\"\xae\x02\n" +
	"\fPlayerReward\x12\x1a\n" +
	"\bPlayerId\x18\x01 \x01(\x03R\bPlayerId\x12*\n" +
	"\x10TemporaryAddress\x18\x02 \x01(\tR\x10TemporaryAddress\x12 \n" +
	"\vTokenChange\x18\x03 \x01(\x05R\vTokenChange\x12 \n" +
	"\vPointChange\x18\x04 \x01(\x05R\vPointChange\x12\x18\n" +
	"\aOffline\x18\x05 \x01(\bR\aOffline\x12 \n" +
	"\vSurrendered\x18\x06 \x01(\bR\vSurrendered\x12V\n" +
	"\x16PlayerGameResultStatus\x18\a \x01(\x0e2\x1e.battle.PlayerGameResultStatusR\x16PlayerGameResultStatus\"h\n" +
	"\fBattleReward\x12:\n" +
	"\rPlayerRewards\x18\x01 \x03(\v2\x14.battle.PlayerRewardR\rPlayerRewards\x12\x1c\n" +
	"\tSystemFee\x18\x02 \x01(\x05R\tSystemFee\"\xac\x02\n" +
	"\n" +
	"GameResult\x12\x1e\n" +
	"\n" +
	"Multiplier\x18\x01 \x01(\x05R\n" +
	"Multiplier\x12&\n" +
	"\x0eWinnerPlayerId\x18\x02 \x01(\x03R\x0eWinnerPlayerId\x126\n" +
	"\x16WinnerTemporaryAddress\x18\x03 \x01(\tR\x16WinnerTemporaryAddress\x12>\n" +
	"\x0eGameResultType\x18\x05 \x01(\x0e2\x16.battle.GameResultTypeR\x0eGameResultType\x12,\n" +
	"\x06Reward\x18\x06 \x01(\v2\x14.battle.BattleRewardR\x06Reward\x120\n" +
	"\x13GameContinueTimeout\x18\a \x01(\x04R\x13GameContinueTimeout\"\xd4\x01\n" +
	"\fBattleEffect\x12,\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x18.battle.BattleEffectTypeR\x04Type\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\x05R\x05Value\x12&\n" +
	"\x0eTargetPlayerId\x18\x03 \x01(\x03R\x0eTargetPlayerId\x126\n" +
	"\x16TargetTemporaryAddress\x18\x04 \x01(\tR\x16TargetTemporaryAddress\x12 \n" +
	"\vDescription\x18\x05 \x01(\tR\vDescription*W\n" +
	"\x0fElementRelation\x12\x0e\n" +
	"\n" +
	"OVER_POWER\x10\x00\x12\x10\n" +
	"\fOVER_POWERED\x10\x01\x12\v\n" +
	"\aNURTURE\x10\x02\x12\f\n" +
	"\bNURTURED\x10\x03\x12\a\n" +
	"\x03TIE\x10\x04*N\n" +
	"\x0eGameResultType\x12\x0f\n" +
	"\vGAME_NORMAL\x10\x00\x12\v\n" +
	"\aGAME_KO\x10\x01\x12\f\n" +
	"\bGAME_TIE\x10\x02\x12\x10\n" +
	"\fGAME_ABORTED\x10\x03*]\n" +
	"\x16PlayerGameResultStatus\x12\x12\n" +
	"\x0ePLAYER_ABORTED\x10\x00\x12\x0e\n" +
	"\n" +
	"PLAYER_WIN\x10\x01\x12\x0f\n" +
	"\vPLAYER_LOSE\x10\x02\x12\x0e\n" +
	"\n" +
	"PLAYER_TIE\x10\x03*(\n" +
	"\x10BattleEffectType\x12\n" +
	"\n" +
	"\x06ATTACK\x10\x00\x12\b\n" +
	"\x04HEAL\x10\x01*\xb2\x02\n" +
	"\x13RoundCompleteReason\x12\x19\n" +
	"\x15ROUND_COMPLETE_NORMAL\x10\x00\x12.\n" +
	"*ROUND_COMPLETE_PLAYER_CONFIRMATION_TIMEOUT\x10\x01\x12-\n" +
	")ROUND_COMPLETE_PLAYER_COMMITMENTS_TIMEOUT\x10\x02\x12'\n" +
	"#ROUND_COMPLETE_PLAYER_CARDS_TIMEOUT\x10\x03\x12'\n" +
	"#ROUND_COMPLETE_SERVER_CHAIN_TIMEOUT\x10\x04\x12*\n" +
	"&ROUND_COMPLETE_SERVER_INTERNAL_TIMEOUT\x10\x05\x12#\n" +
	"\x1fROUND_COMPLETE_PLAYER_SURRENDER\x10\x06B4Z2github.com/CryptoElementals/common/rpc/proto;protob\x06proto3"

var (
	file_rpc_proto_battle_proto_rawDescOnce sync.Once
	file_rpc_proto_battle_proto_rawDescData []byte
)

func file_rpc_proto_battle_proto_rawDescGZIP() []byte {
	file_rpc_proto_battle_proto_rawDescOnce.Do(func() {
		file_rpc_proto_battle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_battle_proto_rawDesc), len(file_rpc_proto_battle_proto_rawDesc)))
	})
	return file_rpc_proto_battle_proto_rawDescData
}

var file_rpc_proto_battle_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_rpc_proto_battle_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rpc_proto_battle_proto_goTypes = []any{
	(ElementRelation)(0),        // 0: battle.ElementRelation
	(GameResultType)(0),         // 1: battle.GameResultType
	(PlayerGameResultStatus)(0), // 2: battle.PlayerGameResultStatus
	(BattleEffectType)(0),       // 3: battle.BattleEffectType
	(RoundCompleteReason)(0),    // 4: battle.RoundCompleteReason
	(*PlayerCardStat)(nil),      // 5: battle.PlayerCardStat
	(*PlayerRoundStat)(nil),     // 6: battle.PlayerRoundStat
	(*RoundResult)(nil),         // 7: battle.RoundResult
	(*PlayerReward)(nil),        // 8: battle.PlayerReward
	(*BattleReward)(nil),        // 9: battle.BattleReward
	(*GameResult)(nil),          // 10: battle.GameResult
	(*BattleEffect)(nil),        // 11: battle.BattleEffect
}
var file_rpc_proto_battle_proto_depIdxs = []int32{
	11, // 0: battle.PlayerCardStat.Effects:type_name -> battle.BattleEffect
	0,  // 1: battle.PlayerCardStat.ElementRelation:type_name -> battle.ElementRelation
	5,  // 2: battle.PlayerRoundStat.CardStats:type_name -> battle.PlayerCardStat
	6,  // 3: battle.RoundResult.Players:type_name -> battle.PlayerRoundStat
	2,  // 4: battle.PlayerReward.PlayerGameResultStatus:type_name -> battle.PlayerGameResultStatus
	8,  // 5: battle.BattleReward.PlayerRewards:type_name -> battle.PlayerReward
	1,  // 6: battle.GameResult.GameResultType:type_name -> battle.GameResultType
	9,  // 7: battle.GameResult.Reward:type_name -> battle.BattleReward
	3,  // 8: battle.BattleEffect.Type:type_name -> battle.BattleEffectType
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_rpc_proto_battle_proto_init() }
func file_rpc_proto_battle_proto_init() {
	if File_rpc_proto_battle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_battle_proto_rawDesc), len(file_rpc_proto_battle_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_proto_battle_proto_goTypes,
		DependencyIndexes: file_rpc_proto_battle_proto_depIdxs,
		EnumInfos:         file_rpc_proto_battle_proto_enumTypes,
		MessageInfos:      file_rpc_proto_battle_proto_msgTypes,
	}.Build()
	File_rpc_proto_battle_proto = out.File
	file_rpc_proto_battle_proto_goTypes = nil
	file_rpc_proto_battle_proto_depIdxs = nil
}
