// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.2
// source: rpc/proto/ledger.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LedgerService_SubmitChainEvents_FullMethodName          = "/rpc.LedgerService/SubmitChainEvents"
	LedgerService_RequestWithdraw_FullMethodName            = "/rpc.LedgerService/RequestWithdraw"
	LedgerService_ListChainTokenLedgers_FullMethodName      = "/rpc.LedgerService/ListChainTokenLedgers"
	LedgerService_GetTokenUnitRates_FullMethodName          = "/rpc.LedgerService/GetTokenUnitRates"
	LedgerService_ConvertTokenAmount_FullMethodName         = "/rpc.LedgerService/ConvertTokenAmount"
	LedgerService_GetWithdrawableTokenAmount_FullMethodName = "/rpc.LedgerService/GetWithdrawableTokenAmount"
)

// LedgerServiceClient is the client API for LedgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LedgerServiceClient interface {
	SubmitChainEvents(ctx context.Context, in *SubmitChainEventsRequest, opts ...grpc.CallOption) (*SubmitChainEventsResponse, error)
	RequestWithdraw(ctx context.Context, in *RequestWithdrawRequest, opts ...grpc.CallOption) (*RequestWithdrawResponse, error)
	ListChainTokenLedgers(ctx context.Context, in *ListChainTokenLedgersRequest, opts ...grpc.CallOption) (*ListChainTokenLedgersResponse, error)
	GetTokenUnitRates(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetTokenUnitRatesResponse, error)
	ConvertTokenAmount(ctx context.Context, in *ConvertTokenAmountRequest, opts ...grpc.CallOption) (*ConvertTokenAmountResponse, error)
	GetWithdrawableTokenAmount(ctx context.Context, in *GetWithdrawableTokenAmountRequest, opts ...grpc.CallOption) (*GetWithdrawableTokenAmountResponse, error)
}

type ledgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLedgerServiceClient(cc grpc.ClientConnInterface) LedgerServiceClient {
	return &ledgerServiceClient{cc}
}

func (c *ledgerServiceClient) SubmitChainEvents(ctx context.Context, in *SubmitChainEventsRequest, opts ...grpc.CallOption) (*SubmitChainEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitChainEventsResponse)
	err := c.cc.Invoke(ctx, LedgerService_SubmitChainEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) RequestWithdraw(ctx context.Context, in *RequestWithdrawRequest, opts ...grpc.CallOption) (*RequestWithdrawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestWithdrawResponse)
	err := c.cc.Invoke(ctx, LedgerService_RequestWithdraw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ListChainTokenLedgers(ctx context.Context, in *ListChainTokenLedgersRequest, opts ...grpc.CallOption) (*ListChainTokenLedgersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChainTokenLedgersResponse)
	err := c.cc.Invoke(ctx, LedgerService_ListChainTokenLedgers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetTokenUnitRates(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetTokenUnitRatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenUnitRatesResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetTokenUnitRates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ConvertTokenAmount(ctx context.Context, in *ConvertTokenAmountRequest, opts ...grpc.CallOption) (*ConvertTokenAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertTokenAmountResponse)
	err := c.cc.Invoke(ctx, LedgerService_ConvertTokenAmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetWithdrawableTokenAmount(ctx context.Context, in *GetWithdrawableTokenAmountRequest, opts ...grpc.CallOption) (*GetWithdrawableTokenAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithdrawableTokenAmountResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetWithdrawableTokenAmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerServiceServer is the server API for LedgerService service.
// All implementations must embed UnimplementedLedgerServiceServer
// for forward compatibility.
type LedgerServiceServer interface {
	SubmitChainEvents(context.Context, *SubmitChainEventsRequest) (*SubmitChainEventsResponse, error)
	RequestWithdraw(context.Context, *RequestWithdrawRequest) (*RequestWithdrawResponse, error)
	ListChainTokenLedgers(context.Context, *ListChainTokenLedgersRequest) (*ListChainTokenLedgersResponse, error)
	GetTokenUnitRates(context.Context, *emptypb.Empty) (*GetTokenUnitRatesResponse, error)
	ConvertTokenAmount(context.Context, *ConvertTokenAmountRequest) (*ConvertTokenAmountResponse, error)
	GetWithdrawableTokenAmount(context.Context, *GetWithdrawableTokenAmountRequest) (*GetWithdrawableTokenAmountResponse, error)
	mustEmbedUnimplementedLedgerServiceServer()
}

// UnimplementedLedgerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLedgerServiceServer struct{}

func (UnimplementedLedgerServiceServer) SubmitChainEvents(context.Context, *SubmitChainEventsRequest) (*SubmitChainEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitChainEvents not implemented")
}
func (UnimplementedLedgerServiceServer) RequestWithdraw(context.Context, *RequestWithdrawRequest) (*RequestWithdrawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestWithdraw not implemented")
}
func (UnimplementedLedgerServiceServer) ListChainTokenLedgers(context.Context, *ListChainTokenLedgersRequest) (*ListChainTokenLedgersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChainTokenLedgers not implemented")
}
func (UnimplementedLedgerServiceServer) GetTokenUnitRates(context.Context, *emptypb.Empty) (*GetTokenUnitRatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenUnitRates not implemented")
}
func (UnimplementedLedgerServiceServer) ConvertTokenAmount(context.Context, *ConvertTokenAmountRequest) (*ConvertTokenAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertTokenAmount not implemented")
}
func (UnimplementedLedgerServiceServer) GetWithdrawableTokenAmount(context.Context, *GetWithdrawableTokenAmountRequest) (*GetWithdrawableTokenAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWithdrawableTokenAmount not implemented")
}
func (UnimplementedLedgerServiceServer) mustEmbedUnimplementedLedgerServiceServer() {}
func (UnimplementedLedgerServiceServer) testEmbeddedByValue()                       {}

// UnsafeLedgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedgerServiceServer will
// result in compilation errors.
type UnsafeLedgerServiceServer interface {
	mustEmbedUnimplementedLedgerServiceServer()
}

func RegisterLedgerServiceServer(s grpc.ServiceRegistrar, srv LedgerServiceServer) {
	// If the following call pancis, it indicates UnimplementedLedgerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LedgerService_ServiceDesc, srv)
}

func _LedgerService_SubmitChainEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitChainEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).SubmitChainEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_SubmitChainEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).SubmitChainEvents(ctx, req.(*SubmitChainEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_RequestWithdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestWithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).RequestWithdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_RequestWithdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).RequestWithdraw(ctx, req.(*RequestWithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ListChainTokenLedgers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChainTokenLedgersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ListChainTokenLedgers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ListChainTokenLedgers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ListChainTokenLedgers(ctx, req.(*ListChainTokenLedgersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetTokenUnitRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetTokenUnitRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetTokenUnitRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetTokenUnitRates(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ConvertTokenAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertTokenAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ConvertTokenAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ConvertTokenAmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ConvertTokenAmount(ctx, req.(*ConvertTokenAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetWithdrawableTokenAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithdrawableTokenAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetWithdrawableTokenAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetWithdrawableTokenAmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetWithdrawableTokenAmount(ctx, req.(*GetWithdrawableTokenAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LedgerService_ServiceDesc is the grpc.ServiceDesc for LedgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LedgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.LedgerService",
	HandlerType: (*LedgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitChainEvents",
			Handler:    _LedgerService_SubmitChainEvents_Handler,
		},
		{
			MethodName: "RequestWithdraw",
			Handler:    _LedgerService_RequestWithdraw_Handler,
		},
		{
			MethodName: "ListChainTokenLedgers",
			Handler:    _LedgerService_ListChainTokenLedgers_Handler,
		},
		{
			MethodName: "GetTokenUnitRates",
			Handler:    _LedgerService_GetTokenUnitRates_Handler,
		},
		{
			MethodName: "ConvertTokenAmount",
			Handler:    _LedgerService_ConvertTokenAmount_Handler,
		},
		{
			MethodName: "GetWithdrawableTokenAmount",
			Handler:    _LedgerService_GetWithdrawableTokenAmount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/proto/ledger.proto",
}
