// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.2
// source: rpc/proto/lobby.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LobbyService_JoinQueue_FullMethodName                                   = "/rpc.LobbyService/JoinQueue"
	LobbyService_ExitQueue_FullMethodName                                   = "/rpc.LobbyService/ExitQueue"
	LobbyService_ConfirmMatch_FullMethodName                                = "/rpc.LobbyService/ConfirmMatch"
	LobbyService_CancelMatch_FullMethodName                                 = "/rpc.LobbyService/CancelMatch"
	LobbyService_GetPlayerStatus_FullMethodName                             = "/rpc.LobbyService/GetPlayerStatus"
	LobbyService_GetPlayerToken_FullMethodName                              = "/rpc.LobbyService/GetPlayerToken"
	LobbyService_RegisterBots_FullMethodName                                = "/rpc.LobbyService/RegisterBots"
	LobbyService_UnregisterBots_FullMethodName                              = "/rpc.LobbyService/UnregisterBots"
	LobbyService_JoinTournament_FullMethodName                              = "/rpc.LobbyService/JoinTournament"
	LobbyService_GetLatestRegistrationOpenTournamentSnapshot_FullMethodName = "/rpc.LobbyService/GetLatestRegistrationOpenTournamentSnapshot"
)

// LobbyServiceClient is the client API for LobbyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LobbyService is served by the lobby server: PVP queue, status, tokens.
// Tournament join/exit RPCs will be added later; tournament logic runs in-process on lobby today.
type LobbyServiceClient interface {
	JoinQueue(ctx context.Context, in *PlayerAddress, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ExitQueue(ctx context.Context, in *PlayerAddress, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ConfirmMatch(ctx context.Context, in *ConfirmMatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CancelMatch(ctx context.Context, in *CancelMatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetPlayerStatus(ctx context.Context, in *PlayerAddress, opts ...grpc.CallOption) (*GetPlayerStatusResponse, error)
	GetPlayerToken(ctx context.Context, in *GetPlayerTokenRequest, opts ...grpc.CallOption) (*GetPlayerTokenResponse, error)
	// Bot queue registration (replaces room PubSub AddBotPlayer/RemoveBotPlayer hooks). Clients may also use lobby PubSub with subscriber_id prefix "bot".
	RegisterBots(ctx context.Context, in *RegisterBotsForLobbyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UnregisterBots(ctx context.Context, in *RegisterBotsForLobbyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// todo: tournament related rpc
	JoinTournament(ctx context.Context, in *JoinTournamentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Latest registration-open tournament snapshot for clients.
	GetLatestRegistrationOpenTournamentSnapshot(ctx context.Context, in *PlayerAddress, opts ...grpc.CallOption) (*GetLatestRegistrationOpenTournamentSnapshotResponse, error)
}

type lobbyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLobbyServiceClient(cc grpc.ClientConnInterface) LobbyServiceClient {
	return &lobbyServiceClient{cc}
}

func (c *lobbyServiceClient) JoinQueue(ctx context.Context, in *PlayerAddress, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LobbyService_JoinQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lobbyServiceClient) ExitQueue(ctx context.Context, in *PlayerAddress, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LobbyService_ExitQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lobbyServiceClient) ConfirmMatch(ctx context.Context, in *ConfirmMatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LobbyService_ConfirmMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lobbyServiceClient) CancelMatch(ctx context.Context, in *CancelMatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LobbyService_CancelMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lobbyServiceClient) GetPlayerStatus(ctx context.Context, in *PlayerAddress, opts ...grpc.CallOption) (*GetPlayerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayerStatusResponse)
	err := c.cc.Invoke(ctx, LobbyService_GetPlayerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lobbyServiceClient) GetPlayerToken(ctx context.Context, in *GetPlayerTokenRequest, opts ...grpc.CallOption) (*GetPlayerTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayerTokenResponse)
	err := c.cc.Invoke(ctx, LobbyService_GetPlayerToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lobbyServiceClient) RegisterBots(ctx context.Context, in *RegisterBotsForLobbyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LobbyService_RegisterBots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lobbyServiceClient) UnregisterBots(ctx context.Context, in *RegisterBotsForLobbyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LobbyService_UnregisterBots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lobbyServiceClient) JoinTournament(ctx context.Context, in *JoinTournamentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LobbyService_JoinTournament_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lobbyServiceClient) GetLatestRegistrationOpenTournamentSnapshot(ctx context.Context, in *PlayerAddress, opts ...grpc.CallOption) (*GetLatestRegistrationOpenTournamentSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestRegistrationOpenTournamentSnapshotResponse)
	err := c.cc.Invoke(ctx, LobbyService_GetLatestRegistrationOpenTournamentSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LobbyServiceServer is the server API for LobbyService service.
// All implementations must embed UnimplementedLobbyServiceServer
// for forward compatibility.
//
// LobbyService is served by the lobby server: PVP queue, status, tokens.
// Tournament join/exit RPCs will be added later; tournament logic runs in-process on lobby today.
type LobbyServiceServer interface {
	JoinQueue(context.Context, *PlayerAddress) (*emptypb.Empty, error)
	ExitQueue(context.Context, *PlayerAddress) (*emptypb.Empty, error)
	ConfirmMatch(context.Context, *ConfirmMatchRequest) (*emptypb.Empty, error)
	CancelMatch(context.Context, *CancelMatchRequest) (*emptypb.Empty, error)
	GetPlayerStatus(context.Context, *PlayerAddress) (*GetPlayerStatusResponse, error)
	GetPlayerToken(context.Context, *GetPlayerTokenRequest) (*GetPlayerTokenResponse, error)
	// Bot queue registration (replaces room PubSub AddBotPlayer/RemoveBotPlayer hooks). Clients may also use lobby PubSub with subscriber_id prefix "bot".
	RegisterBots(context.Context, *RegisterBotsForLobbyRequest) (*emptypb.Empty, error)
	UnregisterBots(context.Context, *RegisterBotsForLobbyRequest) (*emptypb.Empty, error)
	// todo: tournament related rpc
	JoinTournament(context.Context, *JoinTournamentRequest) (*emptypb.Empty, error)
	// Latest registration-open tournament snapshot for clients.
	GetLatestRegistrationOpenTournamentSnapshot(context.Context, *PlayerAddress) (*GetLatestRegistrationOpenTournamentSnapshotResponse, error)
	mustEmbedUnimplementedLobbyServiceServer()
}

// UnimplementedLobbyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLobbyServiceServer struct{}

func (UnimplementedLobbyServiceServer) JoinQueue(context.Context, *PlayerAddress) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinQueue not implemented")
}
func (UnimplementedLobbyServiceServer) ExitQueue(context.Context, *PlayerAddress) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExitQueue not implemented")
}
func (UnimplementedLobbyServiceServer) ConfirmMatch(context.Context, *ConfirmMatchRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmMatch not implemented")
}
func (UnimplementedLobbyServiceServer) CancelMatch(context.Context, *CancelMatchRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelMatch not implemented")
}
func (UnimplementedLobbyServiceServer) GetPlayerStatus(context.Context, *PlayerAddress) (*GetPlayerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerStatus not implemented")
}
func (UnimplementedLobbyServiceServer) GetPlayerToken(context.Context, *GetPlayerTokenRequest) (*GetPlayerTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerToken not implemented")
}
func (UnimplementedLobbyServiceServer) RegisterBots(context.Context, *RegisterBotsForLobbyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterBots not implemented")
}
func (UnimplementedLobbyServiceServer) UnregisterBots(context.Context, *RegisterBotsForLobbyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterBots not implemented")
}
func (UnimplementedLobbyServiceServer) JoinTournament(context.Context, *JoinTournamentRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinTournament not implemented")
}
func (UnimplementedLobbyServiceServer) GetLatestRegistrationOpenTournamentSnapshot(context.Context, *PlayerAddress) (*GetLatestRegistrationOpenTournamentSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestRegistrationOpenTournamentSnapshot not implemented")
}
func (UnimplementedLobbyServiceServer) mustEmbedUnimplementedLobbyServiceServer() {}
func (UnimplementedLobbyServiceServer) testEmbeddedByValue()                      {}

// UnsafeLobbyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LobbyServiceServer will
// result in compilation errors.
type UnsafeLobbyServiceServer interface {
	mustEmbedUnimplementedLobbyServiceServer()
}

func RegisterLobbyServiceServer(s grpc.ServiceRegistrar, srv LobbyServiceServer) {
	// If the following call pancis, it indicates UnimplementedLobbyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LobbyService_ServiceDesc, srv)
}

func _LobbyService_JoinQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).JoinQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_JoinQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).JoinQueue(ctx, req.(*PlayerAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _LobbyService_ExitQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).ExitQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_ExitQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).ExitQueue(ctx, req.(*PlayerAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _LobbyService_ConfirmMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).ConfirmMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_ConfirmMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).ConfirmMatch(ctx, req.(*ConfirmMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LobbyService_CancelMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).CancelMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_CancelMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).CancelMatch(ctx, req.(*CancelMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LobbyService_GetPlayerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).GetPlayerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_GetPlayerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).GetPlayerStatus(ctx, req.(*PlayerAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _LobbyService_GetPlayerToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).GetPlayerToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_GetPlayerToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).GetPlayerToken(ctx, req.(*GetPlayerTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LobbyService_RegisterBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterBotsForLobbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).RegisterBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_RegisterBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).RegisterBots(ctx, req.(*RegisterBotsForLobbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LobbyService_UnregisterBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterBotsForLobbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).UnregisterBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_UnregisterBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).UnregisterBots(ctx, req.(*RegisterBotsForLobbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LobbyService_JoinTournament_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinTournamentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).JoinTournament(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_JoinTournament_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).JoinTournament(ctx, req.(*JoinTournamentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LobbyService_GetLatestRegistrationOpenTournamentSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).GetLatestRegistrationOpenTournamentSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_GetLatestRegistrationOpenTournamentSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).GetLatestRegistrationOpenTournamentSnapshot(ctx, req.(*PlayerAddress))
	}
	return interceptor(ctx, in, info, handler)
}

// LobbyService_ServiceDesc is the grpc.ServiceDesc for LobbyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LobbyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.LobbyService",
	HandlerType: (*LobbyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinQueue",
			Handler:    _LobbyService_JoinQueue_Handler,
		},
		{
			MethodName: "ExitQueue",
			Handler:    _LobbyService_ExitQueue_Handler,
		},
		{
			MethodName: "ConfirmMatch",
			Handler:    _LobbyService_ConfirmMatch_Handler,
		},
		{
			MethodName: "CancelMatch",
			Handler:    _LobbyService_CancelMatch_Handler,
		},
		{
			MethodName: "GetPlayerStatus",
			Handler:    _LobbyService_GetPlayerStatus_Handler,
		},
		{
			MethodName: "GetPlayerToken",
			Handler:    _LobbyService_GetPlayerToken_Handler,
		},
		{
			MethodName: "RegisterBots",
			Handler:    _LobbyService_RegisterBots_Handler,
		},
		{
			MethodName: "UnregisterBots",
			Handler:    _LobbyService_UnregisterBots_Handler,
		},
		{
			MethodName: "JoinTournament",
			Handler:    _LobbyService_JoinTournament_Handler,
		},
		{
			MethodName: "GetLatestRegistrationOpenTournamentSnapshot",
			Handler:    _LobbyService_GetLatestRegistrationOpenTournamentSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/proto/lobby.proto",
}
