// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: rpc/proto/room_worker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoomWorkerService_CreatePvpGameAfterQueueConfirm_FullMethodName = "/rpc.RoomWorkerService/CreatePvpGameAfterQueueConfirm"
	RoomWorkerService_HandleGameMatchedEvent_FullMethodName         = "/rpc.RoomWorkerService/HandleGameMatchedEvent"
	RoomWorkerService_GetPlayerGameStatus_FullMethodName            = "/rpc.RoomWorkerService/GetPlayerGameStatus"
)

// RoomWorkerServiceClient is the client API for RoomWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RoomWorkerService is served by the room server; lobby calls it to create games and read in-game status.
type RoomWorkerServiceClient interface {
	CreatePvpGameAfterQueueConfirm(ctx context.Context, in *CreatePvpGameAfterQueueConfirmRequest, opts ...grpc.CallOption) (*CreatePvpGameAfterQueueConfirmResponse, error)
	HandleGameMatchedEvent(ctx context.Context, in *HandleGameMatchedEventRequest, opts ...grpc.CallOption) (*HandleGameMatchedEventResponse, error)
	GetPlayerGameStatus(ctx context.Context, in *PlayerAddress, opts ...grpc.CallOption) (*GetPlayerGameStatusResponse, error)
}

type roomWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomWorkerServiceClient(cc grpc.ClientConnInterface) RoomWorkerServiceClient {
	return &roomWorkerServiceClient{cc}
}

func (c *roomWorkerServiceClient) CreatePvpGameAfterQueueConfirm(ctx context.Context, in *CreatePvpGameAfterQueueConfirmRequest, opts ...grpc.CallOption) (*CreatePvpGameAfterQueueConfirmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePvpGameAfterQueueConfirmResponse)
	err := c.cc.Invoke(ctx, RoomWorkerService_CreatePvpGameAfterQueueConfirm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomWorkerServiceClient) HandleGameMatchedEvent(ctx context.Context, in *HandleGameMatchedEventRequest, opts ...grpc.CallOption) (*HandleGameMatchedEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleGameMatchedEventResponse)
	err := c.cc.Invoke(ctx, RoomWorkerService_HandleGameMatchedEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomWorkerServiceClient) GetPlayerGameStatus(ctx context.Context, in *PlayerAddress, opts ...grpc.CallOption) (*GetPlayerGameStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayerGameStatusResponse)
	err := c.cc.Invoke(ctx, RoomWorkerService_GetPlayerGameStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomWorkerServiceServer is the server API for RoomWorkerService service.
// All implementations must embed UnimplementedRoomWorkerServiceServer
// for forward compatibility.
//
// RoomWorkerService is served by the room server; lobby calls it to create games and read in-game status.
type RoomWorkerServiceServer interface {
	CreatePvpGameAfterQueueConfirm(context.Context, *CreatePvpGameAfterQueueConfirmRequest) (*CreatePvpGameAfterQueueConfirmResponse, error)
	HandleGameMatchedEvent(context.Context, *HandleGameMatchedEventRequest) (*HandleGameMatchedEventResponse, error)
	GetPlayerGameStatus(context.Context, *PlayerAddress) (*GetPlayerGameStatusResponse, error)
	mustEmbedUnimplementedRoomWorkerServiceServer()
}

// UnimplementedRoomWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoomWorkerServiceServer struct{}

func (UnimplementedRoomWorkerServiceServer) CreatePvpGameAfterQueueConfirm(context.Context, *CreatePvpGameAfterQueueConfirmRequest) (*CreatePvpGameAfterQueueConfirmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePvpGameAfterQueueConfirm not implemented")
}
func (UnimplementedRoomWorkerServiceServer) HandleGameMatchedEvent(context.Context, *HandleGameMatchedEventRequest) (*HandleGameMatchedEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleGameMatchedEvent not implemented")
}
func (UnimplementedRoomWorkerServiceServer) GetPlayerGameStatus(context.Context, *PlayerAddress) (*GetPlayerGameStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerGameStatus not implemented")
}
func (UnimplementedRoomWorkerServiceServer) mustEmbedUnimplementedRoomWorkerServiceServer() {}
func (UnimplementedRoomWorkerServiceServer) testEmbeddedByValue()                           {}

// UnsafeRoomWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomWorkerServiceServer will
// result in compilation errors.
type UnsafeRoomWorkerServiceServer interface {
	mustEmbedUnimplementedRoomWorkerServiceServer()
}

func RegisterRoomWorkerServiceServer(s grpc.ServiceRegistrar, srv RoomWorkerServiceServer) {
	// If the following call pancis, it indicates UnimplementedRoomWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoomWorkerService_ServiceDesc, srv)
}

func _RoomWorkerService_CreatePvpGameAfterQueueConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePvpGameAfterQueueConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomWorkerServiceServer).CreatePvpGameAfterQueueConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomWorkerService_CreatePvpGameAfterQueueConfirm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomWorkerServiceServer).CreatePvpGameAfterQueueConfirm(ctx, req.(*CreatePvpGameAfterQueueConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomWorkerService_HandleGameMatchedEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleGameMatchedEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomWorkerServiceServer).HandleGameMatchedEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomWorkerService_HandleGameMatchedEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomWorkerServiceServer).HandleGameMatchedEvent(ctx, req.(*HandleGameMatchedEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomWorkerService_GetPlayerGameStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomWorkerServiceServer).GetPlayerGameStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomWorkerService_GetPlayerGameStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomWorkerServiceServer).GetPlayerGameStatus(ctx, req.(*PlayerAddress))
	}
	return interceptor(ctx, in, info, handler)
}

// RoomWorkerService_ServiceDesc is the grpc.ServiceDesc for RoomWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.RoomWorkerService",
	HandlerType: (*RoomWorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePvpGameAfterQueueConfirm",
			Handler:    _RoomWorkerService_CreatePvpGameAfterQueueConfirm_Handler,
		},
		{
			MethodName: "HandleGameMatchedEvent",
			Handler:    _RoomWorkerService_HandleGameMatchedEvent_Handler,
		},
		{
			MethodName: "GetPlayerGameStatus",
			Handler:    _RoomWorkerService_GetPlayerGameStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/proto/room_worker.proto",
}
