// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: rpc/proto/rpc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerStatus int32

const (
	PlayerStatus_PLAYER_KNOWN    PlayerStatus = 0
	PlayerStatus_PLAYER_IN_QUEUE PlayerStatus = 1
	PlayerStatus_PLAYER_MATCHED  PlayerStatus = 2
	PlayerStatus_PLAYER_IN_GAME  PlayerStatus = 3
)

// Enum value maps for PlayerStatus.
var (
	PlayerStatus_name = map[int32]string{
		0: "PLAYER_KNOWN",
		1: "PLAYER_IN_QUEUE",
		2: "PLAYER_MATCHED",
		3: "PLAYER_IN_GAME",
	}
	PlayerStatus_value = map[string]int32{
		"PLAYER_KNOWN":    0,
		"PLAYER_IN_QUEUE": 1,
		"PLAYER_MATCHED":  2,
		"PLAYER_IN_GAME":  3,
	}
)

func (x PlayerStatus) Enum() *PlayerStatus {
	p := new(PlayerStatus)
	*p = x
	return p
}

func (x PlayerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_rpc_proto_enumTypes[0].Descriptor()
}

func (PlayerStatus) Type() protoreflect.EnumType {
	return &file_rpc_proto_rpc_proto_enumTypes[0]
}

func (x PlayerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerStatus.Descriptor instead.
func (PlayerStatus) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{0}
}

type RoundStatus int32

const (
	RoundStatus_ROUND_WAITTING_BATTLE_CONFIRMATION RoundStatus = 0
	RoundStatus_ROUND_WAITTING_SETUP_ON_CHAIN      RoundStatus = 1
	RoundStatus_ROUND_WAITTING_COMMITMENTS         RoundStatus = 2
	RoundStatus_ROUND_WAITTING_CARDS               RoundStatus = 3
	RoundStatus_ROUND_COMPLETED                    RoundStatus = 4
)

// Enum value maps for RoundStatus.
var (
	RoundStatus_name = map[int32]string{
		0: "ROUND_WAITTING_BATTLE_CONFIRMATION",
		1: "ROUND_WAITTING_SETUP_ON_CHAIN",
		2: "ROUND_WAITTING_COMMITMENTS",
		3: "ROUND_WAITTING_CARDS",
		4: "ROUND_COMPLETED",
	}
	RoundStatus_value = map[string]int32{
		"ROUND_WAITTING_BATTLE_CONFIRMATION": 0,
		"ROUND_WAITTING_SETUP_ON_CHAIN":      1,
		"ROUND_WAITTING_COMMITMENTS":         2,
		"ROUND_WAITTING_CARDS":               3,
		"ROUND_COMPLETED":                    4,
	}
)

func (x RoundStatus) Enum() *RoundStatus {
	p := new(RoundStatus)
	*p = x
	return p
}

func (x RoundStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoundStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_rpc_proto_enumTypes[1].Descriptor()
}

func (RoundStatus) Type() protoreflect.EnumType {
	return &file_rpc_proto_rpc_proto_enumTypes[1]
}

func (x RoundStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoundStatus.Descriptor instead.
func (RoundStatus) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{1}
}

type GameStatus int32

const (
	GameStatus_GAME_INIT    GameStatus = 0
	GameStatus_GAME_RUNNING GameStatus = 1
	GameStatus_GAME_END     GameStatus = 2
)

// Enum value maps for GameStatus.
var (
	GameStatus_name = map[int32]string{
		0: "GAME_INIT",
		1: "GAME_RUNNING",
		2: "GAME_END",
	}
	GameStatus_value = map[string]int32{
		"GAME_INIT":    0,
		"GAME_RUNNING": 1,
		"GAME_END":     2,
	}
)

func (x GameStatus) Enum() *GameStatus {
	p := new(GameStatus)
	*p = x
	return p
}

func (x GameStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_rpc_proto_enumTypes[2].Descriptor()
}

func (GameStatus) Type() protoreflect.EnumType {
	return &file_rpc_proto_rpc_proto_enumTypes[2]
}

func (x GameStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameStatus.Descriptor instead.
func (GameStatus) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{2}
}

type GameType int32

const (
	GameType_GAME_TYPE_UNKNOWN GameType = 0
	GameType_PVP               GameType = 1
)

// Enum value maps for GameType.
var (
	GameType_name = map[int32]string{
		0: "GAME_TYPE_UNKNOWN",
		1: "PVP",
	}
	GameType_value = map[string]int32{
		"GAME_TYPE_UNKNOWN": 0,
		"PVP":               1,
	}
)

func (x GameType) Enum() *GameType {
	p := new(GameType)
	*p = x
	return p
}

func (x GameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_rpc_proto_enumTypes[3].Descriptor()
}

func (GameType) Type() protoreflect.EnumType {
	return &file_rpc_proto_rpc_proto_enumTypes[3]
}

func (x GameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameType.Descriptor instead.
func (GameType) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{3}
}

type PlayerAddress struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress    string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	TemporaryAddress string                 `protobuf:"bytes,2,opt,name=temporary_address,json=temporaryAddress,proto3" json:"temporary_address,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlayerAddress) Reset() {
	*x = PlayerAddress{}
	mi := &file_rpc_proto_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAddress) ProtoMessage() {}

func (x *PlayerAddress) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAddress.ProtoReflect.Descriptor instead.
func (*PlayerAddress) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerAddress) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *PlayerAddress) GetTemporaryAddress() string {
	if x != nil {
		return x.TemporaryAddress
	}
	return ""
}

type ContinueGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerAddress         `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	LastGameID    uint32                 `protobuf:"varint,2,opt,name=LastGameID,proto3" json:"LastGameID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContinueGameRequest) Reset() {
	*x = ContinueGameRequest{}
	mi := &file_rpc_proto_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueGameRequest) ProtoMessage() {}

func (x *ContinueGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueGameRequest.ProtoReflect.Descriptor instead.
func (*ContinueGameRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *ContinueGameRequest) GetPlayer() *PlayerAddress {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *ContinueGameRequest) GetLastGameID() uint32 {
	if x != nil {
		return x.LastGameID
	}
	return 0
}

type GamePhasePlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *PlayerAddress         `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	IsConfirmed   bool                   `protobuf:"varint,2,opt,name=IsConfirmed,proto3" json:"IsConfirmed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GamePhasePlayer) Reset() {
	*x = GamePhasePlayer{}
	mi := &file_rpc_proto_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GamePhasePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamePhasePlayer) ProtoMessage() {}

func (x *GamePhasePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamePhasePlayer.ProtoReflect.Descriptor instead.
func (*GamePhasePlayer) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *GamePhasePlayer) GetAddress() *PlayerAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *GamePhasePlayer) GetIsConfirmed() bool {
	if x != nil {
		return x.IsConfirmed
	}
	return false
}

type PvPInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GameID          uint32                 `protobuf:"varint,1,opt,name=GameID,proto3" json:"GameID,omitempty"`
	Status          PlayerStatus           `protobuf:"varint,2,opt,name=Status,proto3,enum=rpc.PlayerStatus" json:"Status,omitempty"`
	ContractAddress string                 `protobuf:"bytes,3,opt,name=ContractAddress,proto3" json:"ContractAddress,omitempty"`
	BeginAt         uint64                 `protobuf:"varint,4,opt,name=BeginAt,proto3" json:"BeginAt,omitempty"`
	TimeoutDuration uint64                 `protobuf:"varint,5,opt,name=TimeoutDuration,proto3" json:"TimeoutDuration,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PvPInfo) Reset() {
	*x = PvPInfo{}
	mi := &file_rpc_proto_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PvPInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvPInfo) ProtoMessage() {}

func (x *PvPInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvPInfo.ProtoReflect.Descriptor instead.
func (*PvPInfo) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *PvPInfo) GetGameID() uint32 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *PvPInfo) GetStatus() PlayerStatus {
	if x != nil {
		return x.Status
	}
	return PlayerStatus_PLAYER_KNOWN
}

func (x *PvPInfo) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *PvPInfo) GetBeginAt() uint64 {
	if x != nil {
		return x.BeginAt
	}
	return 0
}

func (x *PvPInfo) GetTimeoutDuration() uint64 {
	if x != nil {
		return x.TimeoutDuration
	}
	return 0
}

type GamePhase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameType      GameType               `protobuf:"varint,1,opt,name=GameType,proto3,enum=rpc.GameType" json:"GameType,omitempty"`
	Players       []*GamePhasePlayer     `protobuf:"bytes,2,rep,name=Players,proto3" json:"Players,omitempty"`
	PvPInfo       *PvPInfo               `protobuf:"bytes,5,opt,name=PvPInfo,proto3" json:"PvPInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GamePhase) Reset() {
	*x = GamePhase{}
	mi := &file_rpc_proto_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GamePhase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamePhase) ProtoMessage() {}

func (x *GamePhase) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamePhase.ProtoReflect.Descriptor instead.
func (*GamePhase) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *GamePhase) GetGameType() GameType {
	if x != nil {
		return x.GameType
	}
	return GameType_GAME_TYPE_UNKNOWN
}

func (x *GamePhase) GetPlayers() []*GamePhasePlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GamePhase) GetPvPInfo() *PvPInfo {
	if x != nil {
		return x.PvPInfo
	}
	return nil
}

type GetBattleInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameID        uint32                 `protobuf:"varint,1,opt,name=GameID,proto3" json:"GameID,omitempty"`
	RoundNumber   uint32                 `protobuf:"varint,2,opt,name=RoundNumber,proto3" json:"RoundNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBattleInfoRequest) Reset() {
	*x = GetBattleInfoRequest{}
	mi := &file_rpc_proto_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBattleInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBattleInfoRequest) ProtoMessage() {}

func (x *GetBattleInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBattleInfoRequest.ProtoReflect.Descriptor instead.
func (*GetBattleInfoRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *GetBattleInfoRequest) GetGameID() uint32 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *GetBattleInfoRequest) GetRoundNumber() uint32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

type GetBattleInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundResult   *RoundResult           `protobuf:"bytes,1,opt,name=round_result,json=roundResult,proto3" json:"round_result,omitempty"`
	GameResult    *GameResult            `protobuf:"bytes,2,opt,name=game_result,json=gameResult,proto3" json:"game_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBattleInfoResponse) Reset() {
	*x = GetBattleInfoResponse{}
	mi := &file_rpc_proto_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBattleInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBattleInfoResponse) ProtoMessage() {}

func (x *GetBattleInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBattleInfoResponse.ProtoReflect.Descriptor instead.
func (*GetBattleInfoResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *GetBattleInfoResponse) GetRoundResult() *RoundResult {
	if x != nil {
		return x.RoundResult
	}
	return nil
}

func (x *GetBattleInfoResponse) GetGameResult() *GameResult {
	if x != nil {
		return x.GameResult
	}
	return nil
}

type ConfirmBattleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerAddress *PlayerAddress         `protobuf:"bytes,1,opt,name=PlayerAddress,proto3" json:"PlayerAddress,omitempty"`
	GameID        uint32                 `protobuf:"varint,2,opt,name=GameID,proto3" json:"GameID,omitempty"`
	RoundNumber   uint32                 `protobuf:"varint,3,opt,name=RoundNumber,proto3" json:"RoundNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmBattleRequest) Reset() {
	*x = ConfirmBattleRequest{}
	mi := &file_rpc_proto_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBattleRequest) ProtoMessage() {}

func (x *ConfirmBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBattleRequest.ProtoReflect.Descriptor instead.
func (*ConfirmBattleRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *ConfirmBattleRequest) GetPlayerAddress() *PlayerAddress {
	if x != nil {
		return x.PlayerAddress
	}
	return nil
}

func (x *ConfirmBattleRequest) GetGameID() uint32 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *ConfirmBattleRequest) GetRoundNumber() uint32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

type PlayerRoundInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PlayerAddress       *PlayerAddress         `protobuf:"bytes,1,opt,name=PlayerAddress,proto3" json:"PlayerAddress,omitempty"`
	PlayerReady         bool                   `protobuf:"varint,2,opt,name=PlayerReady,proto3" json:"PlayerReady,omitempty"`
	Salt                []byte                 `protobuf:"bytes,3,opt,name=Salt,proto3" json:"Salt,omitempty"`
	SubmittedCommitment []byte                 `protobuf:"bytes,4,opt,name=SubmittedCommitment,proto3" json:"SubmittedCommitment,omitempty"`
	SubmittedCards      []*RoundSubmittedCard  `protobuf:"bytes,5,rep,name=SubmittedCards,proto3" json:"SubmittedCards,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PlayerRoundInfo) Reset() {
	*x = PlayerRoundInfo{}
	mi := &file_rpc_proto_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRoundInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRoundInfo) ProtoMessage() {}

func (x *PlayerRoundInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRoundInfo.ProtoReflect.Descriptor instead.
func (*PlayerRoundInfo) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerRoundInfo) GetPlayerAddress() *PlayerAddress {
	if x != nil {
		return x.PlayerAddress
	}
	return nil
}

func (x *PlayerRoundInfo) GetPlayerReady() bool {
	if x != nil {
		return x.PlayerReady
	}
	return false
}

func (x *PlayerRoundInfo) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *PlayerRoundInfo) GetSubmittedCommitment() []byte {
	if x != nil {
		return x.SubmittedCommitment
	}
	return nil
}

func (x *PlayerRoundInfo) GetSubmittedCards() []*RoundSubmittedCard {
	if x != nil {
		return x.SubmittedCards
	}
	return nil
}

type RoundSubmittedCard struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SubmittedCardId    uint32                 `protobuf:"varint,1,opt,name=SubmittedCardId,proto3" json:"SubmittedCardId,omitempty"`
	PlayerHealthBefore uint32                 `protobuf:"varint,2,opt,name=PlayerHealthBefore,proto3" json:"PlayerHealthBefore,omitempty"`
	PlayerHealthEnd    uint32                 `protobuf:"varint,3,opt,name=PlayerHealthEnd,proto3" json:"PlayerHealthEnd,omitempty"`
	MultiplierBefore   uint32                 `protobuf:"varint,4,opt,name=MultiplierBefore,proto3" json:"MultiplierBefore,omitempty"`                           // multiplier before this card
	MultiplierAfter    uint32                 `protobuf:"varint,5,opt,name=MultiplierAfter,proto3" json:"MultiplierAfter,omitempty"`                             // multiplier after this card
	Description        string                 `protobuf:"bytes,6,opt,name=Description,proto3" json:"Description,omitempty"`                                      // battle description
	ElementRelation    ElementRelation        `protobuf:"varint,7,opt,name=ElementRelation,proto3,enum=battle.ElementRelation" json:"ElementRelation,omitempty"` // element relation type
	Effects            []*BattleEffect        `protobuf:"bytes,8,rep,name=Effects,proto3" json:"Effects,omitempty"`                                              // effects applied to this player
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RoundSubmittedCard) Reset() {
	*x = RoundSubmittedCard{}
	mi := &file_rpc_proto_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundSubmittedCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundSubmittedCard) ProtoMessage() {}

func (x *RoundSubmittedCard) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundSubmittedCard.ProtoReflect.Descriptor instead.
func (*RoundSubmittedCard) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *RoundSubmittedCard) GetSubmittedCardId() uint32 {
	if x != nil {
		return x.SubmittedCardId
	}
	return 0
}

func (x *RoundSubmittedCard) GetPlayerHealthBefore() uint32 {
	if x != nil {
		return x.PlayerHealthBefore
	}
	return 0
}

func (x *RoundSubmittedCard) GetPlayerHealthEnd() uint32 {
	if x != nil {
		return x.PlayerHealthEnd
	}
	return 0
}

func (x *RoundSubmittedCard) GetMultiplierBefore() uint32 {
	if x != nil {
		return x.MultiplierBefore
	}
	return 0
}

func (x *RoundSubmittedCard) GetMultiplierAfter() uint32 {
	if x != nil {
		return x.MultiplierAfter
	}
	return 0
}

func (x *RoundSubmittedCard) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoundSubmittedCard) GetElementRelation() ElementRelation {
	if x != nil {
		return x.ElementRelation
	}
	return ElementRelation_OVER_POWER
}

func (x *RoundSubmittedCard) GetEffects() []*BattleEffect {
	if x != nil {
		return x.Effects
	}
	return nil
}

type Round struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Number           int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"` // start from 1
	Status           RoundStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=rpc.RoundStatus" json:"status,omitempty"`
	PlayerRoundInfos []*PlayerRoundInfo     `protobuf:"bytes,3,rep,name=player_round_infos,json=playerRoundInfos,proto3" json:"player_round_infos,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Round) Reset() {
	*x = Round{}
	mi := &file_rpc_proto_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Round) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round) ProtoMessage() {}

func (x *Round) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round.ProtoReflect.Descriptor instead.
func (*Round) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *Round) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Round) GetStatus() RoundStatus {
	if x != nil {
		return x.Status
	}
	return RoundStatus_ROUND_WAITTING_BATTLE_CONFIRMATION
}

func (x *Round) GetPlayerRoundInfos() []*PlayerRoundInfo {
	if x != nil {
		return x.PlayerRoundInfos
	}
	return nil
}

type GameInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	GameId              uint32                 `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	RoomContractAddress string                 `protobuf:"bytes,2,opt,name=room_contract_address,json=roomContractAddress,proto3" json:"room_contract_address,omitempty"`
	GameType            GameType               `protobuf:"varint,3,opt,name=game_type,json=gameType,proto3,enum=rpc.GameType" json:"game_type,omitempty"`
	Status              GameStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=rpc.GameStatus" json:"status,omitempty"`
	InitialHp           int32                  `protobuf:"varint,5,opt,name=initial_hp,json=initialHp,proto3" json:"initial_hp,omitempty"`
	Players             []*PlayerAddress       `protobuf:"bytes,6,rep,name=players,proto3" json:"players,omitempty"`
	Rounds              []*Round               `protobuf:"bytes,7,rep,name=rounds,proto3" json:"rounds,omitempty"`
	Result              *GameResult            `protobuf:"bytes,8,opt,name=result,proto3,oneof" json:"result,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GameInfo) Reset() {
	*x = GameInfo{}
	mi := &file_rpc_proto_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfo) ProtoMessage() {}

func (x *GameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfo.ProtoReflect.Descriptor instead.
func (*GameInfo) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *GameInfo) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GameInfo) GetRoomContractAddress() string {
	if x != nil {
		return x.RoomContractAddress
	}
	return ""
}

func (x *GameInfo) GetGameType() GameType {
	if x != nil {
		return x.GameType
	}
	return GameType_GAME_TYPE_UNKNOWN
}

func (x *GameInfo) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_GAME_INIT
}

func (x *GameInfo) GetInitialHp() int32 {
	if x != nil {
		return x.InitialHp
	}
	return 0
}

func (x *GameInfo) GetPlayers() []*PlayerAddress {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameInfo) GetRounds() []*Round {
	if x != nil {
		return x.Rounds
	}
	return nil
}

func (x *GameInfo) GetResult() *GameResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type Transaction struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TxHash []byte                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	// Types that are valid to be assigned to Tx:
	//
	//	*Transaction_RoomContractCreated
	//	*Transaction_RoomContractSetupReady
	//	*Transaction_CommitmentsOnChain
	//	*Transaction_CardsOnChain
	Tx            isTransaction_Tx `protobuf_oneof:"tx"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_rpc_proto_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *Transaction) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *Transaction) GetTx() isTransaction_Tx {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *Transaction) GetRoomContractCreated() *TxRoomContractCreated {
	if x != nil {
		if x, ok := x.Tx.(*Transaction_RoomContractCreated); ok {
			return x.RoomContractCreated
		}
	}
	return nil
}

func (x *Transaction) GetRoomContractSetupReady() *TxRoomContractRoundSetupReady {
	if x != nil {
		if x, ok := x.Tx.(*Transaction_RoomContractSetupReady); ok {
			return x.RoomContractSetupReady
		}
	}
	return nil
}

func (x *Transaction) GetCommitmentsOnChain() *TxCommitmentsOnChain {
	if x != nil {
		if x, ok := x.Tx.(*Transaction_CommitmentsOnChain); ok {
			return x.CommitmentsOnChain
		}
	}
	return nil
}

func (x *Transaction) GetCardsOnChain() *TxCardsOnChain {
	if x != nil {
		if x, ok := x.Tx.(*Transaction_CardsOnChain); ok {
			return x.CardsOnChain
		}
	}
	return nil
}

type isTransaction_Tx interface {
	isTransaction_Tx()
}

type Transaction_RoomContractCreated struct {
	RoomContractCreated *TxRoomContractCreated `protobuf:"bytes,2,opt,name=room_contract_created,json=roomContractCreated,proto3,oneof"`
}

type Transaction_RoomContractSetupReady struct {
	RoomContractSetupReady *TxRoomContractRoundSetupReady `protobuf:"bytes,3,opt,name=room_contract_setup_ready,json=roomContractSetupReady,proto3,oneof"`
}

type Transaction_CommitmentsOnChain struct {
	CommitmentsOnChain *TxCommitmentsOnChain `protobuf:"bytes,4,opt,name=commitments_on_chain,json=commitmentsOnChain,proto3,oneof"`
}

type Transaction_CardsOnChain struct {
	CardsOnChain *TxCardsOnChain `protobuf:"bytes,5,opt,name=cards_on_chain,json=cardsOnChain,proto3,oneof"`
}

func (*Transaction_RoomContractCreated) isTransaction_Tx() {}

func (*Transaction_RoomContractSetupReady) isTransaction_Tx() {}

func (*Transaction_CommitmentsOnChain) isTransaction_Tx() {}

func (*Transaction_CardsOnChain) isTransaction_Tx() {}

type TransactionBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHash     []byte                 `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionBatch) Reset() {
	*x = TransactionBatch{}
	mi := &file_rpc_proto_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionBatch) ProtoMessage() {}

func (x *TransactionBatch) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionBatch.ProtoReflect.Descriptor instead.
func (*TransactionBatch) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *TransactionBatch) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *TransactionBatch) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TransactionBatch) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *TransactionBatch) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type TxRoomContractCreated struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RoomContractAddress string                 `protobuf:"bytes,1,opt,name=room_contract_address,json=roomContractAddress,proto3" json:"room_contract_address,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TxRoomContractCreated) Reset() {
	*x = TxRoomContractCreated{}
	mi := &file_rpc_proto_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxRoomContractCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxRoomContractCreated) ProtoMessage() {}

func (x *TxRoomContractCreated) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxRoomContractCreated.ProtoReflect.Descriptor instead.
func (*TxRoomContractCreated) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{14}
}

func (x *TxRoomContractCreated) GetRoomContractAddress() string {
	if x != nil {
		return x.RoomContractAddress
	}
	return ""
}

type TxRoomContractRoundSetupReady struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RoomContractAddress string                 `protobuf:"bytes,1,opt,name=room_contract_address,json=roomContractAddress,proto3" json:"room_contract_address,omitempty"`
	RoundNumber         uint32                 `protobuf:"varint,2,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TxRoomContractRoundSetupReady) Reset() {
	*x = TxRoomContractRoundSetupReady{}
	mi := &file_rpc_proto_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxRoomContractRoundSetupReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxRoomContractRoundSetupReady) ProtoMessage() {}

func (x *TxRoomContractRoundSetupReady) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxRoomContractRoundSetupReady.ProtoReflect.Descriptor instead.
func (*TxRoomContractRoundSetupReady) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *TxRoomContractRoundSetupReady) GetRoomContractAddress() string {
	if x != nil {
		return x.RoomContractAddress
	}
	return ""
}

func (x *TxRoomContractRoundSetupReady) GetRoundNumber() uint32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

type TxCommitmentsOnChain struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RoomContractAddress string                 `protobuf:"bytes,1,opt,name=room_contract_address,json=roomContractAddress,proto3" json:"room_contract_address,omitempty"`
	Address             *PlayerAddress         `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	RoundNumber         uint32                 `protobuf:"varint,3,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	Commitment          []byte                 `protobuf:"bytes,4,opt,name=commitment,proto3" json:"commitment,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TxCommitmentsOnChain) Reset() {
	*x = TxCommitmentsOnChain{}
	mi := &file_rpc_proto_rpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxCommitmentsOnChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxCommitmentsOnChain) ProtoMessage() {}

func (x *TxCommitmentsOnChain) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_rpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxCommitmentsOnChain.ProtoReflect.Descriptor instead.
func (*TxCommitmentsOnChain) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{16}
}

func (x *TxCommitmentsOnChain) GetRoomContractAddress() string {
	if x != nil {
		return x.RoomContractAddress
	}
	return ""
}

func (x *TxCommitmentsOnChain) GetAddress() *PlayerAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *TxCommitmentsOnChain) GetRoundNumber() uint32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *TxCommitmentsOnChain) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

type TxCardsOnChain struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RoomContractAddress string                 `protobuf:"bytes,1,opt,name=room_contract_address,json=roomContractAddress,proto3" json:"room_contract_address,omitempty"`
	Address             *PlayerAddress         `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	RoundNumber         uint32                 `protobuf:"varint,3,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	Salt                []byte                 `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"`
	Cards               []uint32               `protobuf:"varint,5,rep,packed,name=cards,proto3" json:"cards,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TxCardsOnChain) Reset() {
	*x = TxCardsOnChain{}
	mi := &file_rpc_proto_rpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxCardsOnChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxCardsOnChain) ProtoMessage() {}

func (x *TxCardsOnChain) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_rpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxCardsOnChain.ProtoReflect.Descriptor instead.
func (*TxCardsOnChain) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{17}
}

func (x *TxCardsOnChain) GetRoomContractAddress() string {
	if x != nil {
		return x.RoomContractAddress
	}
	return ""
}

func (x *TxCardsOnChain) GetAddress() *PlayerAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *TxCardsOnChain) GetRoundNumber() uint32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *TxCardsOnChain) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *TxCardsOnChain) GetCards() []uint32 {
	if x != nil {
		return x.Cards
	}
	return nil
}

var File_rpc_proto_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rpc_proto_rawDesc = "" +
	"\n" +
	"\x13rpc/proto/rpc.proto\x12\x03rpc\x1a\x1bgoogle/protobuf/empty.proto\x1a\x16rpc/proto/battle.proto\"c\n" +
	"\rPlayerAddress\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\x12+\n" +
	"\x11temporary_address\x18\x02 \x01(\tR\x10temporaryAddress\"a\n" +
	"\x13ContinueGameRequest\x12*\n" +
	"\x06player\x18\x01 \x01(\v2\x12.rpc.PlayerAddressR\x06player\x12\x1e\n" +
	"\n" +
	"LastGameID\x18\x02 \x01(\rR\n" +
	"LastGameID\"a\n" +
	"\x0fGamePhasePlayer\x12,\n" +
	"\aAddress\x18\x01 \x01(\v2\x12.rpc.PlayerAddressR\aAddress\x12 \n" +
	"\vIsConfirmed\x18\x02 \x01(\bR\vIsConfirmed\"\xba\x01\n" +
	"\aPvPInfo\x12\x16\n" +
	"\x06GameID\x18\x01 \x01(\rR\x06GameID\x12)\n" +
	"\x06Status\x18\x02 \x01(\x0e2\x11.rpc.PlayerStatusR\x06Status\x12(\n" +
	"\x0fContractAddress\x18\x03 \x01(\tR\x0fContractAddress\x12\x18\n" +
	"\aBeginAt\x18\x04 \x01(\x04R\aBeginAt\x12(\n" +
	"\x0fTimeoutDuration\x18\x05 \x01(\x04R\x0fTimeoutDuration\"\x8e\x01\n" +
	"\tGamePhase\x12)\n" +
	"\bGameType\x18\x01 \x01(\x0e2\r.rpc.GameTypeR\bGameType\x12.\n" +
	"\aPlayers\x18\x02 \x03(\v2\x14.rpc.GamePhasePlayerR\aPlayers\x12&\n" +
	"\aPvPInfo\x18\x05 \x01(\v2\f.rpc.PvPInfoR\aPvPInfo\"P\n" +
	"\x14GetBattleInfoRequest\x12\x16\n" +
	"\x06GameID\x18\x01 \x01(\rR\x06GameID\x12 \n" +
	"\vRoundNumber\x18\x02 \x01(\rR\vRoundNumber\"\x84\x01\n" +
	"\x15GetBattleInfoResponse\x126\n" +
	"\fround_result\x18\x01 \x01(\v2\x13.battle.RoundResultR\vroundResult\x123\n" +
	"\vgame_result\x18\x02 \x01(\v2\x12.battle.GameResultR\n" +
	"gameResult\"\x8a\x01\n" +
	"\x14ConfirmBattleRequest\x128\n" +
	"\rPlayerAddress\x18\x01 \x01(\v2\x12.rpc.PlayerAddressR\rPlayerAddress\x12\x16\n" +
	"\x06GameID\x18\x02 \x01(\rR\x06GameID\x12 \n" +
	"\vRoundNumber\x18\x03 \x01(\rR\vRoundNumber\"\xf4\x01\n" +
	"\x0fPlayerRoundInfo\x128\n" +
	"\rPlayerAddress\x18\x01 \x01(\v2\x12.rpc.PlayerAddressR\rPlayerAddress\x12 \n" +
	"\vPlayerReady\x18\x02 \x01(\bR\vPlayerReady\x12\x12\n" +
	"\x04Salt\x18\x03 \x01(\fR\x04Salt\x120\n" +
	"\x13SubmittedCommitment\x18\x04 \x01(\fR\x13SubmittedCommitment\x12?\n" +
	"\x0eSubmittedCards\x18\x05 \x03(\v2\x17.rpc.RoundSubmittedCardR\x0eSubmittedCards\"\x83\x03\n" +
	"\x12RoundSubmittedCard\x12(\n" +
	"\x0fSubmittedCardId\x18\x01 \x01(\rR\x0fSubmittedCardId\x12.\n" +
	"\x12PlayerHealthBefore\x18\x02 \x01(\rR\x12PlayerHealthBefore\x12(\n" +
	"\x0fPlayerHealthEnd\x18\x03 \x01(\rR\x0fPlayerHealthEnd\x12*\n" +
	"\x10MultiplierBefore\x18\x04 \x01(\rR\x10MultiplierBefore\x12(\n" +
	"\x0fMultiplierAfter\x18\x05 \x01(\rR\x0fMultiplierAfter\x12 \n" +
	"\vDescription\x18\x06 \x01(\tR\vDescription\x12A\n" +
	"\x0fElementRelation\x18\a \x01(\x0e2\x17.battle.ElementRelationR\x0fElementRelation\x12.\n" +
	"\aEffects\x18\b \x03(\v2\x14.battle.BattleEffectR\aEffects\"\x8d\x01\n" +
	"\x05Round\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.rpc.RoundStatusR\x06status\x12B\n" +
	"\x12player_round_infos\x18\x03 \x03(\v2\x14.rpc.PlayerRoundInfoR\x10playerRoundInfos\"\xd9\x02\n" +
	"\bGameInfo\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\rR\x06gameId\x122\n" +
	"\x15room_contract_address\x18\x02 \x01(\tR\x13roomContractAddress\x12*\n" +
	"\tgame_type\x18\x03 \x01(\x0e2\r.rpc.GameTypeR\bgameType\x12'\n" +
	"\x06status\x18\x04 \x01(\x0e2\x0f.rpc.GameStatusR\x06status\x12\x1d\n" +
	"\n" +
	"initial_hp\x18\x05 \x01(\x05R\tinitialHp\x12,\n" +
	"\aplayers\x18\x06 \x03(\v2\x12.rpc.PlayerAddressR\aplayers\x12\"\n" +
	"\x06rounds\x18\a \x03(\v2\n" +
	".rpc.RoundR\x06rounds\x12/\n" +
	"\x06result\x18\b \x01(\v2\x12.battle.GameResultH\x00R\x06result\x88\x01\x01B\t\n" +
	"\a_result\"\xeb\x02\n" +
	"\vTransaction\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\fR\x06txHash\x12P\n" +
	"\x15room_contract_created\x18\x02 \x01(\v2\x1a.rpc.TxRoomContractCreatedH\x00R\x13roomContractCreated\x12_\n" +
	"\x19room_contract_setup_ready\x18\x03 \x01(\v2\".rpc.TxRoomContractRoundSetupReadyH\x00R\x16roomContractSetupReady\x12M\n" +
	"\x14commitments_on_chain\x18\x04 \x01(\v2\x19.rpc.TxCommitmentsOnChainH\x00R\x12commitmentsOnChain\x12;\n" +
	"\x0ecards_on_chain\x18\x05 \x01(\v2\x13.rpc.TxCardsOnChainH\x00R\fcardsOnChainB\x04\n" +
	"\x02tx\"\xa8\x01\n" +
	"\x10TransactionBatch\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\fR\tblockHash\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12!\n" +
	"\fblock_number\x18\x03 \x01(\x04R\vblockNumber\x124\n" +
	"\ftransactions\x18\x04 \x03(\v2\x10.rpc.TransactionR\ftransactions\"K\n" +
	"\x15TxRoomContractCreated\x122\n" +
	"\x15room_contract_address\x18\x01 \x01(\tR\x13roomContractAddress\"v\n" +
	"\x1dTxRoomContractRoundSetupReady\x122\n" +
	"\x15room_contract_address\x18\x01 \x01(\tR\x13roomContractAddress\x12!\n" +
	"\fround_number\x18\x02 \x01(\rR\vroundNumber\"\xbb\x01\n" +
	"\x14TxCommitmentsOnChain\x122\n" +
	"\x15room_contract_address\x18\x01 \x01(\tR\x13roomContractAddress\x12,\n" +
	"\aaddress\x18\x02 \x01(\v2\x12.rpc.PlayerAddressR\aaddress\x12!\n" +
	"\fround_number\x18\x03 \x01(\rR\vroundNumber\x12\x1e\n" +
	"\n" +
	"commitment\x18\x04 \x01(\fR\n" +
	"commitment\"\xbf\x01\n" +
	"\x0eTxCardsOnChain\x122\n" +
	"\x15room_contract_address\x18\x01 \x01(\tR\x13roomContractAddress\x12,\n" +
	"\aaddress\x18\x02 \x01(\v2\x12.rpc.PlayerAddressR\aaddress\x12!\n" +
	"\fround_number\x18\x03 \x01(\rR\vroundNumber\x12\x12\n" +
	"\x04salt\x18\x04 \x01(\fR\x04salt\x12\x14\n" +
	"\x05cards\x18\x05 \x03(\rR\x05cards*]\n" +
	"\fPlayerStatus\x12\x10\n" +
	"\fPLAYER_KNOWN\x10\x00\x12\x13\n" +
	"\x0fPLAYER_IN_QUEUE\x10\x01\x12\x12\n" +
	"\x0ePLAYER_MATCHED\x10\x02\x12\x12\n" +
	"\x0ePLAYER_IN_GAME\x10\x03*\xa7\x01\n" +
	"\vRoundStatus\x12&\n" +
	"\"ROUND_WAITTING_BATTLE_CONFIRMATION\x10\x00\x12!\n" +
	"\x1dROUND_WAITTING_SETUP_ON_CHAIN\x10\x01\x12\x1e\n" +
	"\x1aROUND_WAITTING_COMMITMENTS\x10\x02\x12\x18\n" +
	"\x14ROUND_WAITTING_CARDS\x10\x03\x12\x13\n" +
	"\x0fROUND_COMPLETED\x10\x04*;\n" +
	"\n" +
	"GameStatus\x12\r\n" +
	"\tGAME_INIT\x10\x00\x12\x10\n" +
	"\fGAME_RUNNING\x10\x01\x12\f\n" +
	"\bGAME_END\x10\x02**\n" +
	"\bGameType\x12\x15\n" +
	"\x11GAME_TYPE_UNKNOWN\x10\x00\x12\a\n" +
	"\x03PVP\x10\x012\xc5\x03\n" +
	"\n" +
	"RpcService\x127\n" +
	"\tJoinQueue\x12\x12.rpc.PlayerAddress\x1a\x16.google.protobuf.Empty\x127\n" +
	"\tExitQueue\x12\x12.rpc.PlayerAddress\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\fContinueGame\x12\x18.rpc.ContinueGameRequest\x1a\x16.google.protobuf.Empty\x122\n" +
	"\fGetGamePhase\x12\x12.rpc.PlayerAddress\x1a\x0e.rpc.GamePhase\x12F\n" +
	"\rGetBattleInfo\x12\x19.rpc.GetBattleInfoRequest\x1a\x1a.rpc.GetBattleInfoResponse\x12B\n" +
	"\rConfirmBattle\x12\x19.rpc.ConfirmBattleRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\x12SubmitTransactions\x12\x15.rpc.TransactionBatch\x1a\x16.google.protobuf.EmptyB4Z2github.com/CryptoElementals/common/rpc/proto;protob\x06proto3"

var (
	file_rpc_proto_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rpc_proto_rawDescData []byte
)

func file_rpc_proto_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_rpc_proto_rawDesc), len(file_rpc_proto_rpc_proto_rawDesc)))
	})
	return file_rpc_proto_rpc_proto_rawDescData
}

var file_rpc_proto_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_rpc_proto_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_rpc_proto_rpc_proto_goTypes = []any{
	(PlayerStatus)(0),                     // 0: rpc.PlayerStatus
	(RoundStatus)(0),                      // 1: rpc.RoundStatus
	(GameStatus)(0),                       // 2: rpc.GameStatus
	(GameType)(0),                         // 3: rpc.GameType
	(*PlayerAddress)(nil),                 // 4: rpc.PlayerAddress
	(*ContinueGameRequest)(nil),           // 5: rpc.ContinueGameRequest
	(*GamePhasePlayer)(nil),               // 6: rpc.GamePhasePlayer
	(*PvPInfo)(nil),                       // 7: rpc.PvPInfo
	(*GamePhase)(nil),                     // 8: rpc.GamePhase
	(*GetBattleInfoRequest)(nil),          // 9: rpc.GetBattleInfoRequest
	(*GetBattleInfoResponse)(nil),         // 10: rpc.GetBattleInfoResponse
	(*ConfirmBattleRequest)(nil),          // 11: rpc.ConfirmBattleRequest
	(*PlayerRoundInfo)(nil),               // 12: rpc.PlayerRoundInfo
	(*RoundSubmittedCard)(nil),            // 13: rpc.RoundSubmittedCard
	(*Round)(nil),                         // 14: rpc.Round
	(*GameInfo)(nil),                      // 15: rpc.GameInfo
	(*Transaction)(nil),                   // 16: rpc.Transaction
	(*TransactionBatch)(nil),              // 17: rpc.TransactionBatch
	(*TxRoomContractCreated)(nil),         // 18: rpc.TxRoomContractCreated
	(*TxRoomContractRoundSetupReady)(nil), // 19: rpc.TxRoomContractRoundSetupReady
	(*TxCommitmentsOnChain)(nil),          // 20: rpc.TxCommitmentsOnChain
	(*TxCardsOnChain)(nil),                // 21: rpc.TxCardsOnChain
	(*RoundResult)(nil),                   // 22: battle.RoundResult
	(*GameResult)(nil),                    // 23: battle.GameResult
	(ElementRelation)(0),                  // 24: battle.ElementRelation
	(*BattleEffect)(nil),                  // 25: battle.BattleEffect
	(*emptypb.Empty)(nil),                 // 26: google.protobuf.Empty
}
var file_rpc_proto_rpc_proto_depIdxs = []int32{
	4,  // 0: rpc.ContinueGameRequest.player:type_name -> rpc.PlayerAddress
	4,  // 1: rpc.GamePhasePlayer.Address:type_name -> rpc.PlayerAddress
	0,  // 2: rpc.PvPInfo.Status:type_name -> rpc.PlayerStatus
	3,  // 3: rpc.GamePhase.GameType:type_name -> rpc.GameType
	6,  // 4: rpc.GamePhase.Players:type_name -> rpc.GamePhasePlayer
	7,  // 5: rpc.GamePhase.PvPInfo:type_name -> rpc.PvPInfo
	22, // 6: rpc.GetBattleInfoResponse.round_result:type_name -> battle.RoundResult
	23, // 7: rpc.GetBattleInfoResponse.game_result:type_name -> battle.GameResult
	4,  // 8: rpc.ConfirmBattleRequest.PlayerAddress:type_name -> rpc.PlayerAddress
	4,  // 9: rpc.PlayerRoundInfo.PlayerAddress:type_name -> rpc.PlayerAddress
	13, // 10: rpc.PlayerRoundInfo.SubmittedCards:type_name -> rpc.RoundSubmittedCard
	24, // 11: rpc.RoundSubmittedCard.ElementRelation:type_name -> battle.ElementRelation
	25, // 12: rpc.RoundSubmittedCard.Effects:type_name -> battle.BattleEffect
	1,  // 13: rpc.Round.status:type_name -> rpc.RoundStatus
	12, // 14: rpc.Round.player_round_infos:type_name -> rpc.PlayerRoundInfo
	3,  // 15: rpc.GameInfo.game_type:type_name -> rpc.GameType
	2,  // 16: rpc.GameInfo.status:type_name -> rpc.GameStatus
	4,  // 17: rpc.GameInfo.players:type_name -> rpc.PlayerAddress
	14, // 18: rpc.GameInfo.rounds:type_name -> rpc.Round
	23, // 19: rpc.GameInfo.result:type_name -> battle.GameResult
	18, // 20: rpc.Transaction.room_contract_created:type_name -> rpc.TxRoomContractCreated
	19, // 21: rpc.Transaction.room_contract_setup_ready:type_name -> rpc.TxRoomContractRoundSetupReady
	20, // 22: rpc.Transaction.commitments_on_chain:type_name -> rpc.TxCommitmentsOnChain
	21, // 23: rpc.Transaction.cards_on_chain:type_name -> rpc.TxCardsOnChain
	16, // 24: rpc.TransactionBatch.transactions:type_name -> rpc.Transaction
	4,  // 25: rpc.TxCommitmentsOnChain.address:type_name -> rpc.PlayerAddress
	4,  // 26: rpc.TxCardsOnChain.address:type_name -> rpc.PlayerAddress
	4,  // 27: rpc.RpcService.JoinQueue:input_type -> rpc.PlayerAddress
	4,  // 28: rpc.RpcService.ExitQueue:input_type -> rpc.PlayerAddress
	5,  // 29: rpc.RpcService.ContinueGame:input_type -> rpc.ContinueGameRequest
	4,  // 30: rpc.RpcService.GetGamePhase:input_type -> rpc.PlayerAddress
	9,  // 31: rpc.RpcService.GetBattleInfo:input_type -> rpc.GetBattleInfoRequest
	11, // 32: rpc.RpcService.ConfirmBattle:input_type -> rpc.ConfirmBattleRequest
	17, // 33: rpc.RpcService.SubmitTransactions:input_type -> rpc.TransactionBatch
	26, // 34: rpc.RpcService.JoinQueue:output_type -> google.protobuf.Empty
	26, // 35: rpc.RpcService.ExitQueue:output_type -> google.protobuf.Empty
	26, // 36: rpc.RpcService.ContinueGame:output_type -> google.protobuf.Empty
	8,  // 37: rpc.RpcService.GetGamePhase:output_type -> rpc.GamePhase
	10, // 38: rpc.RpcService.GetBattleInfo:output_type -> rpc.GetBattleInfoResponse
	26, // 39: rpc.RpcService.ConfirmBattle:output_type -> google.protobuf.Empty
	26, // 40: rpc.RpcService.SubmitTransactions:output_type -> google.protobuf.Empty
	34, // [34:41] is the sub-list for method output_type
	27, // [27:34] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_rpc_proto_rpc_proto_init() }
func file_rpc_proto_rpc_proto_init() {
	if File_rpc_proto_rpc_proto != nil {
		return
	}
	file_rpc_proto_battle_proto_init()
	file_rpc_proto_rpc_proto_msgTypes[11].OneofWrappers = []any{}
	file_rpc_proto_rpc_proto_msgTypes[12].OneofWrappers = []any{
		(*Transaction_RoomContractCreated)(nil),
		(*Transaction_RoomContractSetupReady)(nil),
		(*Transaction_CommitmentsOnChain)(nil),
		(*Transaction_CardsOnChain)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rpc_proto_rawDesc), len(file_rpc_proto_rpc_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_rpc_proto_depIdxs,
		EnumInfos:         file_rpc_proto_rpc_proto_enumTypes,
		MessageInfos:      file_rpc_proto_rpc_proto_msgTypes,
	}.Build()
	File_rpc_proto_rpc_proto = out.File
	file_rpc_proto_rpc_proto_goTypes = nil
	file_rpc_proto_rpc_proto_depIdxs = nil
}
