// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/CryptoElementals/common/redis (interfaces: RedisConn,RedisPool)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	redis "github.com/gomodule/redigo/redis"
)

// MockRedisConn is a mock of RedisConn interface.
type MockRedisConn struct {
	ctrl     *gomock.Controller
	recorder *MockRedisConnMockRecorder
}

// MockRedisConnMockRecorder is the mock recorder for MockRedisConn.
type MockRedisConnMockRecorder struct {
	mock *MockRedisConn
}

// NewMockRedisConn creates a new mock instance.
func NewMockRedisConn(ctrl *gomock.Controller) *MockRedisConn {
	mock := &MockRedisConn{ctrl: ctrl}
	mock.recorder = &MockRedisConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisConn) EXPECT() *MockRedisConnMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRedisConn) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRedisConnMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRedisConn)(nil).Close))
}

// Do mocks base method.
func (m *MockRedisConn) Do(arg0 string, arg1 ...interface{}) (interface{}, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Do", varargs...)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockRedisConnMockRecorder) Do(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockRedisConn)(nil).Do), varargs...)
}

// Err mocks base method.
func (m *MockRedisConn) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockRedisConnMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockRedisConn)(nil).Err))
}

// Flush mocks base method.
func (m *MockRedisConn) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockRedisConnMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockRedisConn)(nil).Flush))
}

// Receive mocks base method.
func (m *MockRedisConn) Receive() (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Receive")
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Receive indicates an expected call of Receive.
func (mr *MockRedisConnMockRecorder) Receive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Receive", reflect.TypeOf((*MockRedisConn)(nil).Receive))
}

// Send mocks base method.
func (m *MockRedisConn) Send(arg0 string, arg1 ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Send", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockRedisConnMockRecorder) Send(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockRedisConn)(nil).Send), varargs...)
}

// MockRedisPool is a mock of RedisPool interface.
type MockRedisPool struct {
	ctrl     *gomock.Controller
	recorder *MockRedisPoolMockRecorder
}

// MockRedisPoolMockRecorder is the mock recorder for MockRedisPool.
type MockRedisPoolMockRecorder struct {
	mock *MockRedisPool
}

// NewMockRedisPool creates a new mock instance.
func NewMockRedisPool(ctrl *gomock.Controller) *MockRedisPool {
	mock := &MockRedisPool{ctrl: ctrl}
	mock.recorder = &MockRedisPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisPool) EXPECT() *MockRedisPoolMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRedisPool) Get() redis.Conn {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(redis.Conn)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockRedisPoolMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRedisPool)(nil).Get))
}
