log:
  development: true
  level: debug

redis:
  address: 10.9.23.165:6379
  password: qiaoyunb
  size: 10

server:
  port: 20000
  server-mode: debug
  session-max-age: 5
  refresh-token-max-age: 10
  service-name: test-service