// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/CryptoElementals/common/rpc/server (interfaces: PlayerManager,GameRequestHandler,ChainRequestHandler,PlayerRequestHandler)

// Package testing is a generated GoMock package.
package testing

import (
	context "context"
	reflect "reflect"

	types "github.com/CryptoElementals/common/room_server/worker/types"
	proto "github.com/CryptoElementals/common/rpc/proto"
	gomock "github.com/golang/mock/gomock"
)

// MockPlayerManager is a mock of PlayerManager interface.
type MockPlayerManager struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerManagerMockRecorder
}

// MockPlayerManagerMockRecorder is the mock recorder for MockPlayerManager.
type MockPlayerManagerMockRecorder struct {
	mock *MockPlayerManager
}

// NewMockPlayerManager creates a new mock instance.
func NewMockPlayerManager(ctrl *gomock.Controller) *MockPlayerManager {
	mock := &MockPlayerManager{ctrl: ctrl}
	mock.recorder = &MockPlayerManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayerManager) EXPECT() *MockPlayerManagerMockRecorder {
	return m.recorder
}

// AddBotPlayer mocks base method.
func (m *MockPlayerManager) AddBotPlayer(arg0 types.PlayerAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBotPlayer", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBotPlayer indicates an expected call of AddBotPlayer.
func (mr *MockPlayerManagerMockRecorder) AddBotPlayer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBotPlayer", reflect.TypeOf((*MockPlayerManager)(nil).AddBotPlayer), arg0)
}

// AddPlayer mocks base method.
func (m *MockPlayerManager) AddPlayer(arg0 types.PlayerAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPlayer", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPlayer indicates an expected call of AddPlayer.
func (mr *MockPlayerManagerMockRecorder) AddPlayer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPlayer", reflect.TypeOf((*MockPlayerManager)(nil).AddPlayer), arg0)
}

// RemoveBotPlayer mocks base method.
func (m *MockPlayerManager) RemoveBotPlayer(arg0 types.PlayerAddress) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveBotPlayer", arg0)
}

// RemoveBotPlayer indicates an expected call of RemoveBotPlayer.
func (mr *MockPlayerManagerMockRecorder) RemoveBotPlayer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveBotPlayer", reflect.TypeOf((*MockPlayerManager)(nil).RemoveBotPlayer), arg0)
}

// RemovePlayer mocks base method.
func (m *MockPlayerManager) RemovePlayer(arg0 types.PlayerAddress) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemovePlayer", arg0)
}

// RemovePlayer indicates an expected call of RemovePlayer.
func (mr *MockPlayerManagerMockRecorder) RemovePlayer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePlayer", reflect.TypeOf((*MockPlayerManager)(nil).RemovePlayer), arg0)
}

// MockGameRequestHandler is a mock of GameRequestHandler interface.
type MockGameRequestHandler struct {
	ctrl     *gomock.Controller
	recorder *MockGameRequestHandlerMockRecorder
}

// MockGameRequestHandlerMockRecorder is the mock recorder for MockGameRequestHandler.
type MockGameRequestHandlerMockRecorder struct {
	mock *MockGameRequestHandler
}

// NewMockGameRequestHandler creates a new mock instance.
func NewMockGameRequestHandler(ctrl *gomock.Controller) *MockGameRequestHandler {
	mock := &MockGameRequestHandler{ctrl: ctrl}
	mock.recorder = &MockGameRequestHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameRequestHandler) EXPECT() *MockGameRequestHandlerMockRecorder {
	return m.recorder
}

// GetBattleInfo mocks base method.
func (m *MockGameRequestHandler) GetBattleInfo(arg0 context.Context, arg1, arg2 uint32) (*proto.RoundResult, *proto.GameResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBattleInfo", arg0, arg1, arg2)
	ret0, _ := ret[0].(*proto.RoundResult)
	ret1, _ := ret[1].(*proto.GameResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBattleInfo indicates an expected call of GetBattleInfo.
func (mr *MockGameRequestHandlerMockRecorder) GetBattleInfo(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBattleInfo", reflect.TypeOf((*MockGameRequestHandler)(nil).GetBattleInfo), arg0, arg1, arg2)
}

// GetGamePhase mocks base method.
func (m *MockGameRequestHandler) GetGamePhase(arg0 types.PlayerAddress) (*proto.GamePhase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGamePhase", arg0)
	ret0, _ := ret[0].(*proto.GamePhase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGamePhase indicates an expected call of GetGamePhase.
func (mr *MockGameRequestHandlerMockRecorder) GetGamePhase(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGamePhase", reflect.TypeOf((*MockGameRequestHandler)(nil).GetGamePhase), arg0)
}

// MockChainRequestHandler is a mock of ChainRequestHandler interface.
type MockChainRequestHandler struct {
	ctrl     *gomock.Controller
	recorder *MockChainRequestHandlerMockRecorder
}

// MockChainRequestHandlerMockRecorder is the mock recorder for MockChainRequestHandler.
type MockChainRequestHandlerMockRecorder struct {
	mock *MockChainRequestHandler
}

// NewMockChainRequestHandler creates a new mock instance.
func NewMockChainRequestHandler(ctrl *gomock.Controller) *MockChainRequestHandler {
	mock := &MockChainRequestHandler{ctrl: ctrl}
	mock.recorder = &MockChainRequestHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChainRequestHandler) EXPECT() *MockChainRequestHandlerMockRecorder {
	return m.recorder
}

// SubmitTransactions mocks base method.
func (m *MockChainRequestHandler) SubmitTransactions(arg0 *proto.TransactionBatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitTransactions", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitTransactions indicates an expected call of SubmitTransactions.
func (mr *MockChainRequestHandlerMockRecorder) SubmitTransactions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitTransactions", reflect.TypeOf((*MockChainRequestHandler)(nil).SubmitTransactions), arg0)
}

// MockPlayerRequestHandler is a mock of PlayerRequestHandler interface.
type MockPlayerRequestHandler struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerRequestHandlerMockRecorder
}

// MockPlayerRequestHandlerMockRecorder is the mock recorder for MockPlayerRequestHandler.
type MockPlayerRequestHandlerMockRecorder struct {
	mock *MockPlayerRequestHandler
}

// NewMockPlayerRequestHandler creates a new mock instance.
func NewMockPlayerRequestHandler(ctrl *gomock.Controller) *MockPlayerRequestHandler {
	mock := &MockPlayerRequestHandler{ctrl: ctrl}
	mock.recorder = &MockPlayerRequestHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayerRequestHandler) EXPECT() *MockPlayerRequestHandlerMockRecorder {
	return m.recorder
}

// ConfirmBattle mocks base method.
func (m *MockPlayerRequestHandler) ConfirmBattle(arg0 types.PlayerAddress, arg1 uint, arg2 uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmBattle", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmBattle indicates an expected call of ConfirmBattle.
func (mr *MockPlayerRequestHandlerMockRecorder) ConfirmBattle(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmBattle", reflect.TypeOf((*MockPlayerRequestHandler)(nil).ConfirmBattle), arg0, arg1, arg2)
}

// ContinueGame mocks base method.
func (m *MockPlayerRequestHandler) ContinueGame(arg0 types.PlayerAddress, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContinueGame", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ContinueGame indicates an expected call of ContinueGame.
func (mr *MockPlayerRequestHandlerMockRecorder) ContinueGame(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContinueGame", reflect.TypeOf((*MockPlayerRequestHandler)(nil).ContinueGame), arg0, arg1)
}

// ExitQueue mocks base method.
func (m *MockPlayerRequestHandler) ExitQueue(arg0 types.PlayerAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExitQueue", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExitQueue indicates an expected call of ExitQueue.
func (mr *MockPlayerRequestHandlerMockRecorder) ExitQueue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExitQueue", reflect.TypeOf((*MockPlayerRequestHandler)(nil).ExitQueue), arg0)
}

// IsPlayerInQueue mocks base method.
func (m *MockPlayerRequestHandler) IsPlayerInQueue(arg0 types.PlayerAddress) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPlayerInQueue", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsPlayerInQueue indicates an expected call of IsPlayerInQueue.
func (mr *MockPlayerRequestHandlerMockRecorder) IsPlayerInQueue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPlayerInQueue", reflect.TypeOf((*MockPlayerRequestHandler)(nil).IsPlayerInQueue), arg0)
}

// JoinQueue mocks base method.
func (m *MockPlayerRequestHandler) JoinQueue(arg0 types.PlayerAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinQueue", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// JoinQueue indicates an expected call of JoinQueue.
func (mr *MockPlayerRequestHandlerMockRecorder) JoinQueue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinQueue", reflect.TypeOf((*MockPlayerRequestHandler)(nil).JoinQueue), arg0)
}

// RefuseContinueGame mocks base method.
func (m *MockPlayerRequestHandler) RefuseContinueGame(arg0 types.PlayerAddress, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefuseContinueGame", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefuseContinueGame indicates an expected call of RefuseContinueGame.
func (mr *MockPlayerRequestHandlerMockRecorder) RefuseContinueGame(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefuseContinueGame", reflect.TypeOf((*MockPlayerRequestHandler)(nil).RefuseContinueGame), arg0, arg1)
}

// Surrender mocks base method.
func (m *MockPlayerRequestHandler) Surrender(arg0 types.PlayerAddress, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Surrender", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Surrender indicates an expected call of Surrender.
func (mr *MockPlayerRequestHandlerMockRecorder) Surrender(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Surrender", reflect.TypeOf((*MockPlayerRequestHandler)(nil).Surrender), arg0, arg1)
}
