// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/CryptoElementals/common/rpc/server (interfaces: ChainRequestHandler,PlayerRequestHandler,GamePhaseHandler)

// Package testing is a generated GoMock package.
package testing

import (
	context "context"
	reflect "reflect"

	proto "github.com/CryptoElementals/common/rpc/proto"
	gomock "github.com/golang/mock/gomock"
)

// MockChainRequestHandler is a mock of ChainRequestHandler interface.
type MockChainRequestHandler struct {
	ctrl     *gomock.Controller
	recorder *MockChainRequestHandlerMockRecorder
}

// MockChainRequestHandlerMockRecorder is the mock recorder for MockChainRequestHandler.
type MockChainRequestHandlerMockRecorder struct {
	mock *MockChainRequestHandler
}

// NewMockChainRequestHandler creates a new mock instance.
func NewMockChainRequestHandler(ctrl *gomock.Controller) *MockChainRequestHandler {
	mock := &MockChainRequestHandler{ctrl: ctrl}
	mock.recorder = &MockChainRequestHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChainRequestHandler) EXPECT() *MockChainRequestHandlerMockRecorder {
	return m.recorder
}

// SubmitTransactions mocks base method.
func (m *MockChainRequestHandler) SubmitTransactions(arg0 *proto.TransactionBatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitTransactions", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitTransactions indicates an expected call of SubmitTransactions.
func (mr *MockChainRequestHandlerMockRecorder) SubmitTransactions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitTransactions", reflect.TypeOf((*MockChainRequestHandler)(nil).SubmitTransactions), arg0)
}

// MockPlayerRequestHandler is a mock of PlayerRequestHandler interface.
type MockPlayerRequestHandler struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerRequestHandlerMockRecorder
}

// MockPlayerRequestHandlerMockRecorder is the mock recorder for MockPlayerRequestHandler.
type MockPlayerRequestHandlerMockRecorder struct {
	mock *MockPlayerRequestHandler
}

// NewMockPlayerRequestHandler creates a new mock instance.
func NewMockPlayerRequestHandler(ctrl *gomock.Controller) *MockPlayerRequestHandler {
	mock := &MockPlayerRequestHandler{ctrl: ctrl}
	mock.recorder = &MockPlayerRequestHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayerRequestHandler) EXPECT() *MockPlayerRequestHandlerMockRecorder {
	return m.recorder
}

// ConfirmBattle mocks base method.
func (m *MockPlayerRequestHandler) ConfirmBattle(arg0 *proto.ConfirmBattleRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmBattle", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmBattle indicates an expected call of ConfirmBattle.
func (mr *MockPlayerRequestHandlerMockRecorder) ConfirmBattle(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmBattle", reflect.TypeOf((*MockPlayerRequestHandler)(nil).ConfirmBattle), arg0)
}

// GetBattleInfo mocks base method.
func (m *MockPlayerRequestHandler) GetBattleInfo(arg0 context.Context, arg1 *proto.GetBattleInfoRequest) (*proto.GetBattleInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBattleInfo", arg0, arg1)
	ret0, _ := ret[0].(*proto.GetBattleInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBattleInfo indicates an expected call of GetBattleInfo.
func (mr *MockPlayerRequestHandlerMockRecorder) GetBattleInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBattleInfo", reflect.TypeOf((*MockPlayerRequestHandler)(nil).GetBattleInfo), arg0, arg1)
}

// SubmitPlayerCard mocks base method.
func (m *MockPlayerRequestHandler) SubmitPlayerCard(arg0 *proto.SubmitPlayerCardRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitPlayerCard", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitPlayerCard indicates an expected call of SubmitPlayerCard.
func (mr *MockPlayerRequestHandlerMockRecorder) SubmitPlayerCard(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitPlayerCard", reflect.TypeOf((*MockPlayerRequestHandler)(nil).SubmitPlayerCard), arg0)
}

// SubmitPlayerCommitment mocks base method.
func (m *MockPlayerRequestHandler) SubmitPlayerCommitment(arg0 *proto.SubmitPlayerCommitmentRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitPlayerCommitment", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitPlayerCommitment indicates an expected call of SubmitPlayerCommitment.
func (mr *MockPlayerRequestHandlerMockRecorder) SubmitPlayerCommitment(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitPlayerCommitment", reflect.TypeOf((*MockPlayerRequestHandler)(nil).SubmitPlayerCommitment), arg0)
}

// Surrender mocks base method.
func (m *MockPlayerRequestHandler) Surrender(arg0 *proto.SurrenderRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Surrender", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Surrender indicates an expected call of Surrender.
func (mr *MockPlayerRequestHandlerMockRecorder) Surrender(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Surrender", reflect.TypeOf((*MockPlayerRequestHandler)(nil).Surrender), arg0)
}

// MockGamePhaseHandler is a mock of GamePhaseHandler interface.
type MockGamePhaseHandler struct {
	ctrl     *gomock.Controller
	recorder *MockGamePhaseHandlerMockRecorder
}

// MockGamePhaseHandlerMockRecorder is the mock recorder for MockGamePhaseHandler.
type MockGamePhaseHandlerMockRecorder struct {
	mock *MockGamePhaseHandler
}

// NewMockGamePhaseHandler creates a new mock instance.
func NewMockGamePhaseHandler(ctrl *gomock.Controller) *MockGamePhaseHandler {
	mock := &MockGamePhaseHandler{ctrl: ctrl}
	mock.recorder = &MockGamePhaseHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGamePhaseHandler) EXPECT() *MockGamePhaseHandlerMockRecorder {
	return m.recorder
}

// GetGamePhase mocks base method.
func (m *MockGamePhaseHandler) GetGamePhase(arg0 *proto.PlayerAddress) (*proto.GamePhase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGamePhase", arg0)
	ret0, _ := ret[0].(*proto.GamePhase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGamePhase indicates an expected call of GetGamePhase.
func (mr *MockGamePhaseHandlerMockRecorder) GetGamePhase(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGamePhase", reflect.TypeOf((*MockGamePhaseHandler)(nil).GetGamePhase), arg0)
}
