// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/CryptoElementals/common/room_server/worker/game (interfaces: ContractClient)

// Package testing is a generated GoMock package.
package testing

import (
	reflect "reflect"

	types "github.com/CryptoElementals/common/room_server/worker/types"
	gomock "github.com/golang/mock/gomock"
)

// MockContractClient is a mock of ContractClient interface.
type MockContractClient struct {
	ctrl     *gomock.Controller
	recorder *MockContractClientMockRecorder
}

// MockContractClientMockRecorder is the mock recorder for MockContractClient.
type MockContractClientMockRecorder struct {
	mock *MockContractClient
}

// NewMockContractClient creates a new mock instance.
func NewMockContractClient(ctrl *gomock.Controller) *MockContractClient {
	mock := &MockContractClient{ctrl: ctrl}
	mock.recorder = &MockContractClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractClient) EXPECT() *MockContractClientMockRecorder {
	return m.recorder
}

// CreateRoomContract mocks base method.
func (m *MockContractClient) CreateRoomContract(arg0 *types.RequireContractCreationEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoomContract", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRoomContract indicates an expected call of CreateRoomContract.
func (mr *MockContractClientMockRecorder) CreateRoomContract(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoomContract", reflect.TypeOf((*MockContractClient)(nil).CreateRoomContract), arg0)
}

// SetRoundReady mocks base method.
func (m *MockContractClient) SetRoundReady(arg0 *types.RequireSetupNewRoundEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRoundReady", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRoundReady indicates an expected call of SetRoundReady.
func (mr *MockContractClientMockRecorder) SetRoundReady(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRoundReady", reflect.TypeOf((*MockContractClient)(nil).SetRoundReady), arg0)
}
