// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/CryptoElementals/common/room_server/worker/queue (interfaces: GameCreator)

// Package testing is a generated GoMock package.
package testing

import (
	reflect "reflect"

	types "github.com/CryptoElementals/common/room_server/worker/types"
	gomock "github.com/golang/mock/gomock"
)

// MockGameCreator is a mock of GameCreator interface.
type MockGameCreator struct {
	ctrl     *gomock.Controller
	recorder *MockGameCreatorMockRecorder
}

// MockGameCreatorMockRecorder is the mock recorder for MockGameCreator.
type MockGameCreatorMockRecorder struct {
	mock *MockGameCreator
}

// NewMockGameCreator creates a new mock instance.
func NewMockGameCreator(ctrl *gomock.Controller) *MockGameCreator {
	mock := &MockGameCreator{ctrl: ctrl}
	mock.recorder = &MockGameCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameCreator) EXPECT() *MockGameCreatorMockRecorder {
	return m.recorder
}

// HandleGameContinueEvent mocks base method.
func (m *MockGameCreator) HandleGameContinueEvent(arg0 *types.GameContinueEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleGameContinueEvent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleGameContinueEvent indicates an expected call of HandleGameContinueEvent.
func (mr *MockGameCreatorMockRecorder) HandleGameContinueEvent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGameContinueEvent", reflect.TypeOf((*MockGameCreator)(nil).HandleGameContinueEvent), arg0)
}

// HandleGameMatchedEvent mocks base method.
func (m *MockGameCreator) HandleGameMatchedEvent(arg0 *types.GameMatchedEvent) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleGameMatchedEvent", arg0)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleGameMatchedEvent indicates an expected call of HandleGameMatchedEvent.
func (mr *MockGameCreatorMockRecorder) HandleGameMatchedEvent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGameMatchedEvent", reflect.TypeOf((*MockGameCreator)(nil).HandleGameMatchedEvent), arg0)
}
