// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/CryptoElementals/common/lobby_server/worker/queue (interfaces: GameCreator)

// Package testing is a generated GoMock package.
package testing

import (
	reflect "reflect"

	proto "github.com/CryptoElementals/common/rpc/proto"
	types "github.com/CryptoElementals/common/room_server/worker/types"
	gomock "github.com/golang/mock/gomock"
)

// MockGameCreator is a mock of GameCreator interface.
type MockGameCreator struct {
	ctrl     *gomock.Controller
	recorder *MockGameCreatorMockRecorder
}

// MockGameCreatorMockRecorder is the mock recorder for MockGameCreator.
type MockGameCreatorMockRecorder struct {
	mock *MockGameCreator
}

// NewMockGameCreator creates a new mock instance.
func NewMockGameCreator(ctrl *gomock.Controller) *MockGameCreator {
	mock := &MockGameCreator{ctrl: ctrl}
	mock.recorder = &MockGameCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameCreator) EXPECT() *MockGameCreatorMockRecorder {
	return m.recorder
}

// CreateGameAndRun mocks base method.
func (m *MockGameCreator) CreateGameAndRun(players []types.PlayerAddress, gameType proto.GameType, completedMatchID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGameAndRun", players, gameType, completedMatchID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGameAndRun indicates an expected call of CreateGameAndRun.
func (mr *MockGameCreatorMockRecorder) CreateGameAndRun(players, gameType, completedMatchID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGameAndRun", reflect.TypeOf((*MockGameCreator)(nil).CreateGameAndRun), players, gameType, completedMatchID)
}
