// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/CryptoElementals/common/room_server/worker/player (interfaces: GameInfoGetter,Queuer)

// Package testing is a generated GoMock package.
package testing

import (
	reflect "reflect"

	types "github.com/CryptoElementals/common/room_server/worker/types"
	proto "github.com/CryptoElementals/common/rpc/proto"
	gomock "github.com/golang/mock/gomock"
)

// MockGameInfoGetter is a mock of GameInfoGetter interface.
type MockGameInfoGetter struct {
	ctrl     *gomock.Controller
	recorder *MockGameInfoGetterMockRecorder
}

// MockGameInfoGetterMockRecorder is the mock recorder for MockGameInfoGetter.
type MockGameInfoGetterMockRecorder struct {
	mock *MockGameInfoGetter
}

// NewMockGameInfoGetter creates a new mock instance.
func NewMockGameInfoGetter(ctrl *gomock.Controller) *MockGameInfoGetter {
	mock := &MockGameInfoGetter{ctrl: ctrl}
	mock.recorder = &MockGameInfoGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameInfoGetter) EXPECT() *MockGameInfoGetterMockRecorder {
	return m.recorder
}

// GetActiveGameInfo mocks base method.
func (m *MockGameInfoGetter) GetActiveGameInfo(arg0 types.PlayerAddress) *proto.GameInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveGameInfo", arg0)
	ret0, _ := ret[0].(*proto.GameInfo)
	return ret0
}

// GetActiveGameInfo indicates an expected call of GetActiveGameInfo.
func (mr *MockGameInfoGetterMockRecorder) GetActiveGameInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveGameInfo", reflect.TypeOf((*MockGameInfoGetter)(nil).GetActiveGameInfo), arg0)
}

// GetPlayerGameInfo mocks base method.
func (m *MockGameInfoGetter) GetPlayerGameInfo(arg0 types.PlayerAddress) proto.PlayerStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayerGameInfo", arg0)
	ret0, _ := ret[0].(proto.PlayerStatus)
	return ret0
}

// GetPlayerGameInfo indicates an expected call of GetPlayerGameInfo.
func (mr *MockGameInfoGetterMockRecorder) GetPlayerGameInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayerGameInfo", reflect.TypeOf((*MockGameInfoGetter)(nil).GetPlayerGameInfo), arg0)
}

// MockQueuer is a mock of Queuer interface.
type MockQueuer struct {
	ctrl     *gomock.Controller
	recorder *MockQueuerMockRecorder
}

// MockQueuerMockRecorder is the mock recorder for MockQueuer.
type MockQueuerMockRecorder struct {
	mock *MockQueuer
}

// NewMockQueuer creates a new mock instance.
func NewMockQueuer(ctrl *gomock.Controller) *MockQueuer {
	mock := &MockQueuer{ctrl: ctrl}
	mock.recorder = &MockQueuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueuer) EXPECT() *MockQueuerMockRecorder {
	return m.recorder
}

// HandleContinueGameEvent mocks base method.
func (m *MockQueuer) HandleContinueGameEvent(arg0 *types.PlayerContinueEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleContinueGameEvent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleContinueGameEvent indicates an expected call of HandleContinueGameEvent.
func (mr *MockQueuerMockRecorder) HandleContinueGameEvent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleContinueGameEvent", reflect.TypeOf((*MockQueuer)(nil).HandleContinueGameEvent), arg0)
}

// HandleExitQueueEvent mocks base method.
func (m *MockQueuer) HandleExitQueueEvent(arg0 *types.ExitQueueEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleExitQueueEvent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleExitQueueEvent indicates an expected call of HandleExitQueueEvent.
func (mr *MockQueuerMockRecorder) HandleExitQueueEvent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleExitQueueEvent", reflect.TypeOf((*MockQueuer)(nil).HandleExitQueueEvent), arg0)
}

// HandleJoinQueueEvent mocks base method.
func (m *MockQueuer) HandleJoinQueueEvent(arg0 *types.JoinQueueEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleJoinQueueEvent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleJoinQueueEvent indicates an expected call of HandleJoinQueueEvent.
func (mr *MockQueuerMockRecorder) HandleJoinQueueEvent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleJoinQueueEvent", reflect.TypeOf((*MockQueuer)(nil).HandleJoinQueueEvent), arg0)
}

// IsPlayerInQueue mocks base method.
func (m *MockQueuer) IsPlayerInQueue(arg0 types.PlayerAddress) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPlayerInQueue", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsPlayerInQueue indicates an expected call of IsPlayerInQueue.
func (mr *MockQueuerMockRecorder) IsPlayerInQueue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPlayerInQueue", reflect.TypeOf((*MockQueuer)(nil).IsPlayerInQueue), arg0)
}

// RefuseContinueGame mocks base method.
func (m *MockQueuer) RefuseContinueGame(arg0 types.PlayerAddress, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefuseContinueGame", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefuseContinueGame indicates an expected call of RefuseContinueGame.
func (mr *MockQueuerMockRecorder) RefuseContinueGame(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefuseContinueGame", reflect.TypeOf((*MockQueuer)(nil).RefuseContinueGame), arg0, arg1)
}
