// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/CryptoElementals/common/room_server/worker/game (interfaces: PlayerQueue)

// Package testing is a generated GoMock package.
package testing

import (
	reflect "reflect"

	types "github.com/CryptoElementals/common/room_server/worker/types"
	proto "github.com/CryptoElementals/common/rpc/proto"
	gomock "github.com/golang/mock/gomock"
)

// MockPlayerQueue is a mock of PlayerQueue interface.
type MockPlayerQueue struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerQueueMockRecorder
}

// MockPlayerQueueMockRecorder is the mock recorder for MockPlayerQueue.
type MockPlayerQueueMockRecorder struct {
	mock *MockPlayerQueue
}

// NewMockPlayerQueue creates a new mock instance.
func NewMockPlayerQueue(ctrl *gomock.Controller) *MockPlayerQueue {
	mock := &MockPlayerQueue{ctrl: ctrl}
	mock.recorder = &MockPlayerQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayerQueue) EXPECT() *MockPlayerQueueMockRecorder {
	return m.recorder
}

// HandleConfirmMatch mocks base method.
func (m *MockPlayerQueue) HandleConfirmMatch(arg0 *proto.ConfirmMatchRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleConfirmMatch", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleConfirmMatch indicates an expected call of HandleConfirmMatch.
func (mr *MockPlayerQueueMockRecorder) HandleConfirmMatch(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleConfirmMatch", reflect.TypeOf((*MockPlayerQueue)(nil).HandleConfirmMatch), arg0)
}

// HandleCancelMatch mocks base method.
func (m *MockPlayerQueue) HandleCancelMatch(arg0 *proto.CancelMatchRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCancelMatch", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleCancelMatch indicates an expected call of HandleCancelMatch.
func (mr *MockPlayerQueueMockRecorder) HandleCancelMatch(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCancelMatch", reflect.TypeOf((*MockPlayerQueue)(nil).HandleCancelMatch), arg0)
}

// HandleExitQueueEvent mocks base method.
func (m *MockPlayerQueue) HandleExitQueueEvent(arg0 *proto.PlayerAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleExitQueueEvent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleExitQueueEvent indicates an expected call of HandleExitQueueEvent.
func (mr *MockPlayerQueueMockRecorder) HandleExitQueueEvent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleExitQueueEvent", reflect.TypeOf((*MockPlayerQueue)(nil).HandleExitQueueEvent), arg0)
}

// HandleJoinQueueEvent mocks base method.
func (m *MockPlayerQueue) HandleJoinQueueEvent(arg0 *proto.PlayerAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleJoinQueueEvent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleJoinQueueEvent indicates an expected call of HandleJoinQueueEvent.
func (mr *MockPlayerQueueMockRecorder) HandleJoinQueueEvent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleJoinQueueEvent", reflect.TypeOf((*MockPlayerQueue)(nil).HandleJoinQueueEvent), arg0)
}

// IsPlayerInQueue mocks base method.
func (m *MockPlayerQueue) IsPlayerInQueue(arg0 types.PlayerAddress) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPlayerInQueue", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsPlayerInQueue indicates an expected call of IsPlayerInQueue.
func (mr *MockPlayerQueueMockRecorder) IsPlayerInQueue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPlayerInQueue", reflect.TypeOf((*MockPlayerQueue)(nil).IsPlayerInQueue), arg0)
}

// IsPlayerPendingMatch mocks base method.
func (m *MockPlayerQueue) IsPlayerPendingMatch(arg0 types.PlayerAddress) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPlayerPendingMatch", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsPlayerPendingMatch indicates an expected call of IsPlayerPendingMatch.
func (mr *MockPlayerQueueMockRecorder) IsPlayerPendingMatch(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPlayerPendingMatch", reflect.TypeOf((*MockPlayerQueue)(nil).IsPlayerPendingMatch), arg0)
}

// RegisterBots mocks base method.
func (m *MockPlayerQueue) RegisterBots(arg0 ...*types.PlayerAddress) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterBots", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterBots indicates an expected call of RegisterBots.
func (mr *MockPlayerQueueMockRecorder) RegisterBots(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterBots", reflect.TypeOf((*MockPlayerQueue)(nil).RegisterBots), arg0...)
}

// UnregisterBots mocks base method.
func (m *MockPlayerQueue) UnregisterBots(arg0 ...*types.PlayerAddress) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UnregisterBots", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterBots indicates an expected call of UnregisterBots.
func (mr *MockPlayerQueueMockRecorder) UnregisterBots(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterBots", reflect.TypeOf((*MockPlayerQueue)(nil).UnregisterBots), arg0...)
}
