// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/CryptoElementals/common/room_server/worker/player (interfaces: GameInfoGetter,QueueInfoGetter)

// Package testing is a generated GoMock package.
package testing

import (
	reflect "reflect"

	types "github.com/CryptoElementals/common/room_server/worker/types"
	proto "github.com/CryptoElementals/common/rpc/proto"
	gomock "github.com/golang/mock/gomock"
)

// MockGameInfoGetter is a mock of GameInfoGetter interface.
type MockGameInfoGetter struct {
	ctrl     *gomock.Controller
	recorder *MockGameInfoGetterMockRecorder
}

// MockGameInfoGetterMockRecorder is the mock recorder for MockGameInfoGetter.
type MockGameInfoGetterMockRecorder struct {
	mock *MockGameInfoGetter
}

// NewMockGameInfoGetter creates a new mock instance.
func NewMockGameInfoGetter(ctrl *gomock.Controller) *MockGameInfoGetter {
	mock := &MockGameInfoGetter{ctrl: ctrl}
	mock.recorder = &MockGameInfoGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameInfoGetter) EXPECT() *MockGameInfoGetterMockRecorder {
	return m.recorder
}

// GetActiveGameInfo mocks base method.
func (m *MockGameInfoGetter) GetActiveGameInfo(arg0 types.PlayerAddress) *proto.GameInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveGameInfo", arg0)
	ret0, _ := ret[0].(*proto.GameInfo)
	return ret0
}

// GetActiveGameInfo indicates an expected call of GetActiveGameInfo.
func (mr *MockGameInfoGetterMockRecorder) GetActiveGameInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveGameInfo", reflect.TypeOf((*MockGameInfoGetter)(nil).GetActiveGameInfo), arg0)
}

// GetPlayerGameInfo mocks base method.
func (m *MockGameInfoGetter) GetPlayerGameInfo(arg0 types.PlayerAddress) proto.PlayerStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayerGameInfo", arg0)
	ret0, _ := ret[0].(proto.PlayerStatus)
	return ret0
}

// GetPlayerGameInfo indicates an expected call of GetPlayerGameInfo.
func (mr *MockGameInfoGetterMockRecorder) GetPlayerGameInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayerGameInfo", reflect.TypeOf((*MockGameInfoGetter)(nil).GetPlayerGameInfo), arg0)
}

// MockQueueInfoGetter is a mock of QueueInfoGetter interface.
type MockQueueInfoGetter struct {
	ctrl     *gomock.Controller
	recorder *MockQueueInfoGetterMockRecorder
}

// MockQueueInfoGetterMockRecorder is the mock recorder for MockQueueInfoGetter.
type MockQueueInfoGetterMockRecorder struct {
	mock *MockQueueInfoGetter
}

// NewMockQueueInfoGetter creates a new mock instance.
func NewMockQueueInfoGetter(ctrl *gomock.Controller) *MockQueueInfoGetter {
	mock := &MockQueueInfoGetter{ctrl: ctrl}
	mock.recorder = &MockQueueInfoGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueInfoGetter) EXPECT() *MockQueueInfoGetterMockRecorder {
	return m.recorder
}

// IsPlayerInQueue mocks base method.
func (m *MockQueueInfoGetter) IsPlayerInQueue(arg0 types.PlayerAddress) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPlayerInQueue", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsPlayerInQueue indicates an expected call of IsPlayerInQueue.
func (mr *MockQueueInfoGetterMockRecorder) IsPlayerInQueue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPlayerInQueue", reflect.TypeOf((*MockQueueInfoGetter)(nil).IsPlayerInQueue), arg0)
}
