// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/CryptoElementals/common/room_server/worker/player (interfaces: GameInfoGetter,Queuer)

// Package testing is a generated GoMock package.
package testing

import (
	context "context"
	reflect "reflect"

	types "github.com/CryptoElementals/common/room_server/worker/types"
	proto "github.com/CryptoElementals/common/rpc/proto"
	gomock "github.com/golang/mock/gomock"
)

// MockGameInfoGetter is a mock of GameInfoGetter interface.
type MockGameInfoGetter struct {
	ctrl     *gomock.Controller
	recorder *MockGameInfoGetterMockRecorder
}

// MockGameInfoGetterMockRecorder is the mock recorder for MockGameInfoGetter.
type MockGameInfoGetterMockRecorder struct {
	mock *MockGameInfoGetter
}

// NewMockGameInfoGetter creates a new mock instance.
func NewMockGameInfoGetter(ctrl *gomock.Controller) *MockGameInfoGetter {
	mock := &MockGameInfoGetter{ctrl: ctrl}
	mock.recorder = &MockGameInfoGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameInfoGetter) EXPECT() *MockGameInfoGetterMockRecorder {
	return m.recorder
}

// GetActiveGameInfo mocks base method.
func (m *MockGameInfoGetter) GetActiveGameInfo(arg0 types.PlayerAddress) *proto.GameInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveGameInfo", arg0)
	ret0, _ := ret[0].(*proto.GameInfo)
	return ret0
}

// GetActiveGameInfo indicates an expected call of GetActiveGameInfo.
func (mr *MockGameInfoGetterMockRecorder) GetActiveGameInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveGameInfo", reflect.TypeOf((*MockGameInfoGetter)(nil).GetActiveGameInfo), arg0)
}

// GetBattleInfo mocks base method.
func (m *MockGameInfoGetter) GetBattleInfo(arg0 context.Context, arg1, arg2 uint32) (*proto.RoundResult, *proto.GameResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBattleInfo", arg0, arg1, arg2)
	ret0, _ := ret[0].(*proto.RoundResult)
	ret1, _ := ret[1].(*proto.GameResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBattleInfo indicates an expected call of GetBattleInfo.
func (mr *MockGameInfoGetterMockRecorder) GetBattleInfo(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBattleInfo", reflect.TypeOf((*MockGameInfoGetter)(nil).GetBattleInfo), arg0, arg1, arg2)
}

// GetGamePhase mocks base method.
func (m *MockGameInfoGetter) GetGamePhase(arg0 types.PlayerAddress) (*proto.GamePhase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGamePhase", arg0)
	ret0, _ := ret[0].(*proto.GamePhase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGamePhase indicates an expected call of GetGamePhase.
func (mr *MockGameInfoGetterMockRecorder) GetGamePhase(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGamePhase", reflect.TypeOf((*MockGameInfoGetter)(nil).GetGamePhase), arg0)
}

// GetPlayerGameInfo mocks base method.
func (m *MockGameInfoGetter) GetPlayerGameInfo(arg0 types.PlayerAddress) proto.PlayerStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayerGameInfo", arg0)
	ret0, _ := ret[0].(proto.PlayerStatus)
	return ret0
}

// GetPlayerGameInfo indicates an expected call of GetPlayerGameInfo.
func (mr *MockGameInfoGetterMockRecorder) GetPlayerGameInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayerGameInfo", reflect.TypeOf((*MockGameInfoGetter)(nil).GetPlayerGameInfo), arg0)
}

// HandleSubmitPlayerCard mocks base method.
func (m *MockGameInfoGetter) HandleSubmitPlayerCard(arg0 *types.SubmitPlayerCard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleSubmitPlayerCard", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleSubmitPlayerCard indicates an expected call of HandleSubmitPlayerCard.
func (mr *MockGameInfoGetterMockRecorder) HandleSubmitPlayerCard(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSubmitPlayerCard", reflect.TypeOf((*MockGameInfoGetter)(nil).HandleSubmitPlayerCard), arg0)
}

// HandleSubmitPlayerCommitment mocks base method.
func (m *MockGameInfoGetter) HandleSubmitPlayerCommitment(arg0 *types.SubmitPlayerCommitment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleSubmitPlayerCommitment", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleSubmitPlayerCommitment indicates an expected call of HandleSubmitPlayerCommitment.
func (mr *MockGameInfoGetterMockRecorder) HandleSubmitPlayerCommitment(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSubmitPlayerCommitment", reflect.TypeOf((*MockGameInfoGetter)(nil).HandleSubmitPlayerCommitment), arg0)
}

// MockQueuer is a mock of Queuer interface.
type MockQueuer struct {
	ctrl     *gomock.Controller
	recorder *MockQueuerMockRecorder
}

// MockQueuerMockRecorder is the mock recorder for MockQueuer.
type MockQueuerMockRecorder struct {
	mock *MockQueuer
}

// NewMockQueuer creates a new mock instance.
func NewMockQueuer(ctrl *gomock.Controller) *MockQueuer {
	mock := &MockQueuer{ctrl: ctrl}
	mock.recorder = &MockQueuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueuer) EXPECT() *MockQueuerMockRecorder {
	return m.recorder
}

// GetPlayerContinueInfo mocks base method.
func (m *MockQueuer) GetPlayerContinueInfo(arg0 types.PlayerAddress) *types.GameContinueInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayerContinueInfo", arg0)
	ret0, _ := ret[0].(*types.GameContinueInfo)
	return ret0
}

// GetPlayerContinueInfo indicates an expected call of GetPlayerContinueInfo.
func (mr *MockQueuerMockRecorder) GetPlayerContinueInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayerContinueInfo", reflect.TypeOf((*MockQueuer)(nil).GetPlayerContinueInfo), arg0)
}

// HandleContinueGameEvent mocks base method.
func (m *MockQueuer) HandleContinueGameEvent(arg0 *types.PlayerContinueEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleContinueGameEvent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleContinueGameEvent indicates an expected call of HandleContinueGameEvent.
func (mr *MockQueuerMockRecorder) HandleContinueGameEvent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleContinueGameEvent", reflect.TypeOf((*MockQueuer)(nil).HandleContinueGameEvent), arg0)
}

// HandleExitQueueEvent mocks base method.
func (m *MockQueuer) HandleExitQueueEvent(arg0 *types.ExitQueueEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleExitQueueEvent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleExitQueueEvent indicates an expected call of HandleExitQueueEvent.
func (mr *MockQueuerMockRecorder) HandleExitQueueEvent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleExitQueueEvent", reflect.TypeOf((*MockQueuer)(nil).HandleExitQueueEvent), arg0)
}

// HandleJoinQueueEvent mocks base method.
func (m *MockQueuer) HandleJoinQueueEvent(arg0 *types.JoinQueueEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleJoinQueueEvent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleJoinQueueEvent indicates an expected call of HandleJoinQueueEvent.
func (mr *MockQueuerMockRecorder) HandleJoinQueueEvent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleJoinQueueEvent", reflect.TypeOf((*MockQueuer)(nil).HandleJoinQueueEvent), arg0)
}

// IsPlayerInQueue mocks base method.
func (m *MockQueuer) IsPlayerInQueue(arg0 types.PlayerAddress) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPlayerInQueue", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsPlayerInQueue indicates an expected call of IsPlayerInQueue.
func (mr *MockQueuerMockRecorder) IsPlayerInQueue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPlayerInQueue", reflect.TypeOf((*MockQueuer)(nil).IsPlayerInQueue), arg0)
}

// RefuseContinueGame mocks base method.
func (m *MockQueuer) RefuseContinueGame(arg0 types.PlayerAddress, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefuseContinueGame", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefuseContinueGame indicates an expected call of RefuseContinueGame.
func (mr *MockQueuerMockRecorder) RefuseContinueGame(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefuseContinueGame", reflect.TypeOf((*MockQueuer)(nil).RefuseContinueGame), arg0, arg1)
}

// RegisterBots mocks base method.
func (m *MockQueuer) RegisterBots(arg0 ...*types.PlayerAddress) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterBots", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterBots indicates an expected call of RegisterBots.
func (mr *MockQueuerMockRecorder) RegisterBots(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterBots", reflect.TypeOf((*MockQueuer)(nil).RegisterBots), arg0...)
}

// UnregisterBots mocks base method.
func (m *MockQueuer) UnregisterBots(arg0 ...*types.PlayerAddress) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UnregisterBots", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterBots indicates an expected call of UnregisterBots.
func (mr *MockQueuerMockRecorder) UnregisterBots(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterBots", reflect.TypeOf((*MockQueuer)(nil).UnregisterBots), arg0...)
}
