// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/CryptoElementals/common/room_server/worker/game (interfaces: ContractClient)

// Package testing is a generated GoMock package.
package testing

import (
	reflect "reflect"

	types "github.com/CryptoElementals/common/room_server/worker/types"
	gomock "github.com/golang/mock/gomock"
)

// MockContractClient is a mock of ContractClient interface.
type MockContractClient struct {
	ctrl     *gomock.Controller
	recorder *MockContractClientMockRecorder
}

// MockContractClientMockRecorder is the mock recorder for MockContractClient.
type MockContractClientMockRecorder struct {
	mock *MockContractClient
}

// NewMockContractClient creates a new mock instance.
func NewMockContractClient(ctrl *gomock.Controller) *MockContractClient {
	mock := &MockContractClient{ctrl: ctrl}
	mock.recorder = &MockContractClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractClient) EXPECT() *MockContractClientMockRecorder {
	return m.recorder
}

// SubmitTasks mocks base method.
func (m *MockContractClient) SubmitTasks(arg0 [][]byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitTasks", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitTasks indicates an expected call of SubmitTasks.
func (mr *MockContractClientMockRecorder) SubmitTasks(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitTasks", reflect.TypeOf((*MockContractClient)(nil).SubmitTasks), arg0)
}

// CreateRoomContract mocks base method.
func (m *MockContractClient) CreateRoomContract(arg0 *types.RequireGameCreationEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoomContract", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRoomContract indicates an expected call of CreateRoomContract.
func (mr *MockContractClientMockRecorder) CreateRoomContract(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoomContract", reflect.TypeOf((*MockContractClient)(nil).CreateRoomContract), arg0)
}

// SetTurnReady mocks base method.
func (m *MockContractClient) SetTurnReady(arg0 *types.RequireSetupNewTurnEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTurnReady", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTurnReady indicates an expected call of SetTurnReady.
func (mr *MockContractClientMockRecorder) SetTurnReady(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTurnReady", reflect.TypeOf((*MockContractClient)(nil).SetTurnReady), arg0)
}

// SubmitPlayerCardsBatch mocks base method.
func (m *MockContractClient) SubmitPlayerCardsBatch(arg0 []*types.SubmitPlayerCard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitPlayerCardsBatch", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitPlayerCardsBatch indicates an expected call of SubmitPlayerCardsBatch.
func (mr *MockContractClientMockRecorder) SubmitPlayerCardsBatch(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitPlayerCardsBatch", reflect.TypeOf((*MockContractClient)(nil).SubmitPlayerCardsBatch), arg0)
}

// SubmitPlayerCommitmentsBatch mocks base method.
func (m *MockContractClient) SubmitPlayerCommitmentsBatch(arg0 []*types.SubmitPlayerCommitment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitPlayerCommitmentsBatch", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitPlayerCommitmentsBatch indicates an expected call of SubmitPlayerCommitmentsBatch.
func (mr *MockContractClientMockRecorder) SubmitPlayerCommitmentsBatch(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitPlayerCommitmentsBatch", reflect.TypeOf((*MockContractClient)(nil).SubmitPlayerCommitmentsBatch), arg0)
}
